/*******************************************************************************
 * Copyright (c) 2026 Groovy Language Server Contributors.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
package org.eclipse.groovy.ls.core.providers;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.lang.reflect.Modifier;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.codehaus.groovy.ast.ClassNode;
import org.codehaus.groovy.ast.ImportNode;
import org.codehaus.groovy.ast.MethodNode;
import org.codehaus.groovy.ast.ModuleNode;
import org.codehaus.groovy.ast.Parameter;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.groovy.ls.core.DocumentManager;
import org.eclipse.groovy.ls.core.GroovyLanguageServerPlugin;
import org.eclipse.jdt.core.IMethod;
import org.eclipse.jdt.core.IJavaProject;
import org.eclipse.jdt.core.ISourceRange;
import org.eclipse.jdt.core.ISourceReference;
import org.eclipse.jdt.core.IType;
import org.eclipse.jdt.core.JavaCore;
import org.eclipse.jdt.core.JavaModelException;
import org.eclipse.jdt.core.search.IJavaSearchConstants;
import org.eclipse.jdt.core.search.IJavaSearchScope;
import org.eclipse.jdt.core.search.SearchEngine;
import org.eclipse.jdt.core.search.SearchPattern;
import org.eclipse.jdt.core.search.TypeNameMatch;
import org.eclipse.jdt.core.search.TypeNameMatchRequestor;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.lsp4j.*;
import org.eclipse.lsp4j.jsonrpc.messages.Either;

/**
 * Provides LSP code actions for Groovy documents.
 * <p>
 * Supported actions:
 * <ul>
 *   <li><b>Remove unused import</b> — triggered from unused import warnings</li>
 *   <li><b>Delete unused declaration</b> — removes unused types and methods</li>
 *   <li><b>Organize imports</b> — removes unused imports, adds missing imports,
 *       and sorts simple imports</li>
 *   <li><b>Add import</b> — suggests imports for unresolved type references
 *       (searches the JDT classpath index for matching types)</li>
 *   <li><b>Create type</b> — creates a class/interface/trait/enum in the
 *       current workspace source root</li>
 *   <li><b>Implement inherited abstract members</b> — generates stubs for
 *       missing abstract methods from interfaces and abstract superclasses</li>
 * </ul>
 */
public class CodeActionProvider {

    /** Diagnostic code for unused imports (generated by our DiagnosticsProvider). */
    public static final String DIAG_CODE_UNUSED_IMPORT = "groovy.unusedImport";
    /** Diagnostic code for unused declarations (generated by UnusedDeclarationDetector). */
    public static final String DIAG_CODE_UNUSED_DECLARATION = "groovy.unusedDeclaration";
    /** Diagnostic code prefix for unresolved types. */
    public static final String DIAG_CODE_UNRESOLVED_TYPE = "groovy.unresolvedType";
    /** Source action kind for adding all missing imports. */
    public static final String SOURCE_KIND_ADD_MISSING_IMPORTS = "source.addMissingImports";
    /** Source action kind for removing all unused imports. */
    public static final String SOURCE_KIND_REMOVE_UNUSED_IMPORTS = "source.removeUnusedImports";
    /** Source action kind for applying all safe automatic fixes. */
    public static final String SOURCE_KIND_FIX_ALL_GROOVY = "source.fixAll.groovy";

    /** Maximum number of import suggestions to return per unresolved type. */
    private static final int MAX_IMPORT_SUGGESTIONS = 10;
    private static final String IMPORT_PREFIX = "import ";
    private static final String PACKAGE_PREFIX = "package ";
    private static final String LINE_SEPARATOR = "\n";
    private static final String TYPE_MESSAGE_MARKER = "The type ";
    private static final Pattern PACKAGE_DECLARATION_PATTERN = Pattern.compile(
            "(?m)^\\s*package\\s+([\\w.]+)\\s*;?\\s*$");
    private static final Pattern SIMPLE_IMPORT_PATTERN = Pattern.compile(
            "^import\\s+([\\w$.]+)\\s*;?\\s*$");
    private static final String[] SOURCE_ROOT_SEGMENTS = {
            "/src/main/groovy/",
            "/src/main/java/",
            "/src/test/groovy/",
            "/src/test/java/",
            "/src/groovy/",
            "/src/java/",
            "/src/"
    };
    /** Data key used to mark code actions that need lazy resolve. */
    public static final String RESOLVE_KIND_ADD_IMPORT = "groovy.addImport";

    private final DocumentManager documentManager;
    private final DiagnosticsProvider diagnosticsProvider;

    /**
     * LRU cache for import search results, keyed by "simpleName#projectName".
     * Avoids redundant JDT SearchEngine scans when the same type is searched
     * in createAddImportActions and again in collectMissingImports.
     * Entries expire after 60 s (checked on read).
     */
    private static final int IMPORT_CACHE_MAX = 200;
    private static final long IMPORT_CACHE_TTL_MS = 60_000;

    private static final class CachedSearchResult {
        final List<String> results;
        final long timestamp;
        CachedSearchResult(List<String> results) {
            this.results = results;
            this.timestamp = System.currentTimeMillis();
        }
        boolean isExpired() {
            return System.currentTimeMillis() - timestamp > IMPORT_CACHE_TTL_MS;
        }
    }

    @SuppressWarnings("serial")
    private final Map<String, CachedSearchResult> importSearchCache =
            Collections.synchronizedMap(
                    new java.util.LinkedHashMap<String, CachedSearchResult>(
                            IMPORT_CACHE_MAX + 1, 0.75f, true) {
                        @Override
                        protected boolean removeEldestEntry(
                                Map.Entry<String, CachedSearchResult> eldest) {
                            return size() > IMPORT_CACHE_MAX;
                        }
                    });

    public CodeActionProvider(DocumentManager documentManager,
            DiagnosticsProvider diagnosticsProvider) {
        this.documentManager = documentManager;
        this.diagnosticsProvider = diagnosticsProvider;
    }

    public void invalidateCache() {
        importSearchCache.clear();
    }

    private static String getDiagnosticCode(Diagnostic diag) {
        if (diag.getCode() == null) return null;
        if (diag.getCode().isLeft()) return diag.getCode().getLeft();
        if (diag.getCode().isRight()) return String.valueOf(diag.getCode().getRight());
        return null;
    }

    /**
     * Compute code actions for the given request.
     */
    public List<Either<Command, CodeAction>> getCodeActions(CodeActionParams params) {
        CodeActionRequest request = buildCodeActionRequest(params);
        if (request == null) {
            return new ArrayList<>();
        }

        List<Either<Command, CodeAction>> actions = new ArrayList<>();
        if (request.wantQuickfix) {
            addQuickFixActions(actions, request);
        }
        if (request.wantSource) {
            addSourceActions(actions, request);
        }
        return actions;
    }

    private CodeActionRequest buildCodeActionRequest(CodeActionParams params) {
        String uri = params.getTextDocument().getUri();
        String content = documentManager.getContent(uri);
        if (content == null) {
            return null;
        }

        List<String> onlyKinds = params.getContext().getOnly() != null
                ? params.getContext().getOnly()
                : null;
        boolean wantQuickfix = wantsQuickFix(onlyKinds);
        boolean wantSource = wantsSource(onlyKinds);

        List<Diagnostic> diagnostics = params.getContext().getDiagnostics();
        List<Diagnostic> requestDiagnostics = diagnostics != null ? diagnostics : new ArrayList<>();
        requestDiagnostics = ensureDiagnosticsForRequest(uri, requestDiagnostics, wantQuickfix, wantSource);

        // Reuse the same diagnostics for allDiagnostics — avoids a second
        // (potentially expensive) diagnostic collection call.
        List<Diagnostic> allDiagnostics = requestDiagnostics.isEmpty()
                ? getLatestDiagnosticsOnly(uri)
                : requestDiagnostics;
        return new CodeActionRequest(uri, content, params.getRange(), onlyKinds, requestDiagnostics,
                allDiagnostics, wantQuickfix, wantSource);
    }

    private boolean wantsQuickFix(List<String> onlyKinds) {
        return onlyKinds == null || onlyKinds.contains(CodeActionKind.QuickFix);
    }

    private boolean wantsSource(List<String> onlyKinds) {
        return onlyKinds == null
                || onlyKinds.contains(CodeActionKind.Source)
                || onlyKinds.contains(CodeActionKind.SourceOrganizeImports)
                || onlyKinds.contains(CodeActionKind.SourceFixAll)
                || onlyKinds.contains(SOURCE_KIND_FIX_ALL_GROOVY)
                || onlyKinds.contains(SOURCE_KIND_ADD_MISSING_IMPORTS)
                || onlyKinds.contains(SOURCE_KIND_REMOVE_UNUSED_IMPORTS);
    }

    private List<Diagnostic> ensureDiagnosticsForRequest(String uri,
            List<Diagnostic> diagnostics,
            boolean wantQuickfix,
            boolean wantSource) {
        if ((!wantQuickfix && !wantSource) || !diagnostics.isEmpty()) {
            return diagnostics;
        }
        return getLatestDiagnosticsOnly(uri);
    }

    /**
     * Return cached diagnostics only — never trigger a full JDT reconcile.
     * Code actions should work with whatever diagnostics are already available
     * (either cached from the last didChange cycle, or provided by the client
     * in the request context). Triggering reconcile from here frequently
     * caused 5–15 s hangs that exceeded the 15 s code-action timeout.
     */
    private List<Diagnostic> getLatestDiagnosticsOnly(String uri) {
        return diagnosticsProvider.getLatestDiagnostics(uri);
    }

    private void addQuickFixActions(List<Either<Command, CodeAction>> actions, CodeActionRequest request) {
        for (Diagnostic diagnostic : request.requestDiagnostics) {
            addPerDiagnosticQuickFixes(actions, request.uri, request.content, request.range, diagnostic);
        }

        addAction(actions,
                createRemoveAllUnusedImportsQuickFixAction(
                        request.uri,
                        request.content,
                        request.requestDiagnostics));
        addAction(actions,
                createAddAllMissingImportsQuickFixAction(
                        request.uri,
                        request.content,
                        request.allDiagnostics));
    }

    private void addPerDiagnosticQuickFixes(List<Either<Command, CodeAction>> actions,
            String uri,
            String content,
            Range requestRange,
            Diagnostic diagnostic) {
        String code = getDiagnosticCode(diagnostic);
        boolean cursorOnSymbol = intersects(requestRange, diagnostic.getRange());
        if (DIAG_CODE_UNUSED_IMPORT.equals(code)) {
            addAction(actions, createRemoveImportAction(uri, content, diagnostic, cursorOnSymbol));
        }

        if (DIAG_CODE_UNUSED_DECLARATION.equals(code)) {
            addAction(actions, createDeleteUnusedDeclarationAction(uri, content, diagnostic, cursorOnSymbol));
        }

        if (isUnresolvedTypeDiagnostic(diagnostic)) {
            addActions(actions, createAddImportActions(uri, content, diagnostic));
            addActions(actions, createCreateTypeActions(uri, content, diagnostic));
        }

        if (isMissingInterfaceMemberDiagnostic(diagnostic)) {
            addAction(actions,
                    createImplementMissingInterfaceMembersAction(uri, content, diagnostic));
        }
    }

    private void addSourceActions(List<Either<Command, CodeAction>> actions, CodeActionRequest request) {
        addAction(actions,
                createOrganizeImportsAction(
                        request.uri,
                        request.content,
                        request.allDiagnostics,
                        request.onlyKinds));
        addAction(actions,
                createRemoveAllUnusedImportsAction(request.uri, request.content, request.onlyKinds));
        addAction(actions,
                createAddAllMissingImportsAction(
                        request.uri,
                        request.content,
                        request.allDiagnostics,
                        request.onlyKinds));
        addAction(actions,
                createFixAllAction(
                        request.uri,
                        request.content,
                        request.allDiagnostics,
                        request.onlyKinds));
    }

    private void addAction(List<Either<Command, CodeAction>> actions, CodeAction action) {
        if (action != null) {
            actions.add(Either.forRight(action));
        }
    }

    private void addActions(List<Either<Command, CodeAction>> actions, List<CodeAction> codeActions) {
        for (CodeAction action : codeActions) {
            actions.add(Either.forRight(action));
        }
    }

    // ================================================================
    // Remove unused import
    // ================================================================

    private CodeAction createRemoveImportAction(String uri, String content, Diagnostic diag,
            boolean preferred) {
        try {
            Range importRange = diag.getRange();
            // Expand to full line (including the newline)
            int startLine = importRange.getStart().getLine();
            String[] lines = content.split("\n", -1);
            if (startLine < 0 || startLine >= lines.length) return null;

            Range fullLineRange = new Range(
                    new Position(startLine, 0),
                    new Position(startLine + 1, 0));

            TextEdit removeEdit = new TextEdit(fullLineRange, "");

            CodeAction action = new CodeAction("Remove unused import");
            action.setKind(CodeActionKind.QuickFix);
            action.setDiagnostics(Collections.singletonList(diag));
            action.setIsPreferred(preferred);

            WorkspaceEdit edit = new WorkspaceEdit();
            edit.setChanges(Collections.singletonMap(uri, Collections.singletonList(removeEdit)));
            action.setEdit(edit);

            return action;
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError("Failed to create remove import action", e);
            return null;
        }
    }

    // ================================================================
    // Add import for unresolved type
    // ================================================================

    private CodeAction createDeleteUnusedDeclarationAction(String uri, String content,
            Diagnostic diag, boolean preferred) {
        try {
            Range declarationRange = findUnusedDeclarationRange(uri, content, diag);
            if (declarationRange == null) {
                return null;
            }

            TextEdit removeEdit = new TextEdit(declarationRange, "");

            CodeAction action = new CodeAction("Delete unused declaration");
            action.setKind(CodeActionKind.QuickFix);
            action.setDiagnostics(Collections.singletonList(diag));
            action.setIsPreferred(preferred);

            WorkspaceEdit edit = new WorkspaceEdit();
            edit.setChanges(Collections.singletonMap(uri, Collections.singletonList(removeEdit)));
            action.setEdit(edit);
            return action;
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError("Failed to create delete unused declaration action", e);
            return null;
        }
    }

    private Range findUnusedDeclarationRange(String uri, String content, Diagnostic diag)
            throws JavaModelException {
        if (diag == null || diag.getRange() == null) {
            return null;
        }

        org.eclipse.jdt.core.ICompilationUnit workingCopy = documentManager.getWorkingCopy(uri);
        if (workingCopy == null) {
            return null;
        }

        boolean methodDiagnostic = isUnusedMethodDiagnostic(diag);
        for (IType type : workingCopy.getTypes()) {
            Range match = findUnusedDeclarationRange(type, content, diag.getRange(), methodDiagnostic);
            if (match != null) {
                return match;
            }
        }
        return null;
    }

    private Range findUnusedDeclarationRange(IType type, String content, Range diagnosticRange,
            boolean methodDiagnostic)
            throws JavaModelException {
        if (methodDiagnostic) {
            for (IMethod method : type.getMethods()) {
                Range methodRange = matchUnusedDeclarationRange(method, content, diagnosticRange);
                if (methodRange != null) {
                    return methodRange;
                }
            }

            for (IType innerType : type.getTypes()) {
                Range nested = findUnusedDeclarationRange(innerType, content, diagnosticRange, true);
                if (nested != null) {
                    return nested;
                }
            }
            return null;
        }

        Range typeRange = matchUnusedDeclarationRange(type, content, diagnosticRange);
        if (typeRange != null) {
            return typeRange;
        }

        for (IType innerType : type.getTypes()) {
            Range nested = findUnusedDeclarationRange(innerType, content, diagnosticRange, false);
            if (nested != null) {
                return nested;
            }
        }

        return null;
    }

    private Range matchUnusedDeclarationRange(ISourceReference sourceRef, String content,
            Range diagnosticRange) throws JavaModelException {
        if (sourceRef == null) {
            return null;
        }

        ISourceRange nameRange = sourceRef.getNameRange();
        ISourceRange sourceRange = sourceRef.getSourceRange();
        if (nameRange == null || sourceRange == null
                || nameRange.getOffset() < 0 || sourceRange.getOffset() < 0) {
            return null;
        }

        PositionUtils.LineIndex lineIndex = PositionUtils.buildLineIndex(content);
        Range nameLspRange = new Range(
                lineIndex.offsetToPosition(nameRange.getOffset()),
                lineIndex.offsetToPosition(nameRange.getOffset() + nameRange.getLength()));
        if (!intersects(nameLspRange, diagnosticRange)) {
            return null;
        }

        int sourceStart = sourceRange.getOffset();
        int sourceEnd = sourceStart + sourceRange.getLength();
        return expandToWholeLines(content, sourceStart, sourceEnd);
    }

    private Range expandToWholeLines(String content, int startOffset, int endOffset) {
        int boundedStart = Math.max(0, Math.min(startOffset, content.length()));
        int boundedEnd = Math.max(boundedStart, Math.min(endOffset, content.length()));

        int lineStart = content.lastIndexOf('\n', Math.max(0, boundedStart - 1));
        lineStart = lineStart < 0 ? 0 : lineStart + 1;

        int lineEndSearchFrom = Math.max(lineStart, Math.max(0, boundedEnd - 1));
        int lineEnd = content.indexOf('\n', lineEndSearchFrom);
        lineEnd = lineEnd < 0 ? content.length() : lineEnd + 1;

        while (lineEnd < content.length()) {
            int nextLineEnd = content.indexOf('\n', lineEnd);
            int scanEnd = nextLineEnd < 0 ? content.length() : nextLineEnd;
            String nextLine = content.substring(lineEnd, scanEnd);
            if (!nextLine.trim().isEmpty()) {
                break;
            }
            lineEnd = nextLineEnd < 0 ? content.length() : nextLineEnd + 1;
        }

        PositionUtils.LineIndex lineIndex = PositionUtils.buildLineIndex(content);
        return new Range(lineIndex.offsetToPosition(lineStart), lineIndex.offsetToPosition(lineEnd));
    }

    private List<CodeAction> createAddImportActions(String uri, String content, Diagnostic diag) {
        List<CodeAction> actions = new ArrayList<>();

        try {
            // Extract the type name from the diagnostic message
            Object msgObj = diag.getMessage();
            String message = msgObj != null ? msgObj.toString() : null;
            String typeName = extractTypeNameFromMessage(message);
            if (typeName == null || typeName.isEmpty()) return actions;

            // Search the JDT classpath index for matching types
            List<String> candidates = searchClasspathForType(typeName, uri);

            // Also check imports already present to avoid duplicates
            Set<String> existingImports = getExistingImports(uri);

            for (String fqn : candidates) {
                if (existingImports.contains(fqn)) continue;

                // Return a lightweight code action with data — the actual
                // WorkspaceEdit is computed lazily in resolveCodeAction()
                // so that the code-action list appears instantly.
                CodeAction action = new CodeAction("Import '" + fqn + "'");
                action.setKind(CodeActionKind.QuickFix);
                action.setDiagnostics(Collections.singletonList(diag));

                com.google.gson.JsonObject data = new com.google.gson.JsonObject();
                data.addProperty("resolve", RESOLVE_KIND_ADD_IMPORT);
                data.addProperty("uri", uri);
                data.addProperty("fqn", fqn);
                action.setData(data);

                actions.add(action);
            }
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError("Failed to create add import actions", e);
        }

        return actions;
    }

    private List<CodeAction> createCreateTypeActions(String uri, String content, Diagnostic diag) {
        List<CodeAction> actions = new ArrayList<>();

        try {
            String unresolvedCandidate = extractUnresolvedTypeCandidate(getDiagnosticMessage(diag));
            if (unresolvedCandidate == null || unresolvedCandidate.isEmpty()) {
                return actions;
            }

            String simpleName = simpleTypeName(unresolvedCandidate);
            if (!isValidTypeIdentifier(simpleName)) {
                return actions;
            }

            String currentPackage = getCurrentPackageName(content);
            String targetPackage = unresolvedCandidate.contains(".")
                    ? unresolvedCandidate.substring(0, unresolvedCandidate.lastIndexOf('.'))
                    : currentPackage;
            Path targetPath = resolveNewTypePath(uri, currentPackage, targetPackage, simpleName);
            if (targetPath == null || Files.exists(targetPath)) {
                return actions;
            }

            String targetUri = targetPath.toUri().toString();
            actions.add(createCreateTypeAction("class", simpleName, targetPackage, targetUri, diag));
            actions.add(createCreateTypeAction("interface", simpleName, targetPackage, targetUri, diag));
            actions.add(createCreateTypeAction("trait", simpleName, targetPackage, targetUri, diag));
            actions.add(createCreateTypeAction("enum", simpleName, targetPackage, targetUri, diag));
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError("Failed to create unresolved type creation actions", e);
        }

        return actions;
    }

    private CodeAction createCreateTypeAction(String kind, String simpleName, String packageName,
            String targetUri, Diagnostic diag) {
        String source = buildNewTypeSource(kind, simpleName, packageName);
        CreateFile createFile = new CreateFile(targetUri);
        TextEdit initialContent = new TextEdit(
                new Range(new Position(0, 0), new Position(0, 0)),
                source);
        TextDocumentEdit docEdit = new TextDocumentEdit(
                new VersionedTextDocumentIdentifier(targetUri, null),
                List.of(Either.forLeft(initialContent)));

        WorkspaceEdit edit = new WorkspaceEdit();
        edit.setDocumentChanges(List.of(
                Either.forRight(createFile),
                Either.forLeft(docEdit)));

        CodeAction action = new CodeAction("Create " + kind + " '" + simpleName + "'");
        action.setKind(CodeActionKind.QuickFix);
        action.setDiagnostics(Collections.singletonList(diag));
        action.setEdit(edit);
        return action;
    }

    private String buildNewTypeSource(String kind, String simpleName, String packageName) {
        StringBuilder sb = new StringBuilder();
        if (packageName != null && !packageName.isBlank()) {
            sb.append(PACKAGE_PREFIX).append(packageName).append(LINE_SEPARATOR).append(LINE_SEPARATOR);
        }
        sb.append(kind).append(' ').append(simpleName).append(" {").append(LINE_SEPARATOR);
        sb.append("}").append(LINE_SEPARATOR);
        return sb.toString();
    }

    /**
     * Resolve a deferred code action by computing its WorkspaceEdit.
     * Called by the LSP {@code codeAction/resolve} handler.
     */
    public CodeAction resolveCodeAction(CodeAction codeAction) {
        Object rawData = codeAction.getData();
        if (rawData == null) return codeAction;

        com.google.gson.JsonObject data;
        if (rawData instanceof com.google.gson.JsonObject jo) {
            data = jo;
        } else {
            // LSP4J may deserialise data as a generic JsonElement
            try {
                data = com.google.gson.JsonParser.parseString(rawData.toString()).getAsJsonObject();
            } catch (Exception e) {
                return codeAction;
            }
        }

        String resolveKind = data.has("resolve") ? data.get("resolve").getAsString() : null;
        if (!RESOLVE_KIND_ADD_IMPORT.equals(resolveKind)) {
            return codeAction;
        }

        String uri = data.has("uri") ? data.get("uri").getAsString() : null;
        String fqn = data.has("fqn") ? data.get("fqn").getAsString() : null;
        if (uri == null || fqn == null) return codeAction;

        String content = documentManager.getContent(uri);
        if (content == null) return codeAction;

        int insertLine = findImportInsertLine(content);
        String importStatement = IMPORT_PREFIX + fqn + LINE_SEPARATOR;
        TextEdit insertEdit = new TextEdit(
                new Range(new Position(insertLine, 0), new Position(insertLine, 0)),
                importStatement);

        WorkspaceEdit edit = new WorkspaceEdit();
        edit.setChanges(Collections.singletonMap(uri, Collections.singletonList(insertEdit)));
        codeAction.setEdit(edit);

        return codeAction;
    }

    private CodeAction createAddAllMissingImportsAction(String uri, String content,
            List<Diagnostic> diagnostics, List<String> onlyKinds) {
        if (!wantsKind(onlyKinds, CodeActionKind.Source, SOURCE_KIND_ADD_MISSING_IMPORTS)) {
            return null;
        }

        try {
            Set<String> existingImports = getExistingImports(uri);
            MissingImportsResult missingImports =
                    collectMissingImports(uri, diagnostics, existingImports);
            Set<String> importsToAdd = missingImports.importsToAdd;
            List<Diagnostic> matchedDiagnostics = missingImports.matchedDiagnostics;

            if (importsToAdd.size() < 2) {
                return null;
            }

            int insertLine = findImportInsertLine(content);
            String importBlock = buildImportBlock(importsToAdd);

            TextEdit insertEdit = new TextEdit(
                    new Range(new Position(insertLine, 0), new Position(insertLine, 0)),
                    importBlock);

            CodeAction action = new CodeAction("Add all missing imports");
            action.setKind(SOURCE_KIND_ADD_MISSING_IMPORTS);
            action.setDiagnostics(matchedDiagnostics);

            WorkspaceEdit edit = new WorkspaceEdit();
            edit.setChanges(Collections.singletonMap(uri, Collections.singletonList(insertEdit)));
            action.setEdit(edit);

            return action;
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError("Failed to create add all missing imports action", e);
            return null;
        }
    }

    /**
     * Search the JDT classpath index for types matching the given simple name.
     * Returns a list of fully qualified type names found on the project's classpath.
     * Results are cached (LRU, 60 s TTL) to avoid duplicate searches within
     * the same code-action request cycle.
     */
    private List<String> searchClasspathForType(String simpleName, String uri) {
        // Check the cache first
        List<IJavaProject> javaProjects = getSearchProjectsForUri(uri);
        String projectKey = javaProjects.isEmpty()
                ? simpleName
                : simpleName + "#" + javaProjects.get(0).getElementName();
        CachedSearchResult cached = importSearchCache.get(projectKey);
        if (cached != null && !cached.isExpired()) {
            return new ArrayList<>(cached.results);
        }

        List<String> results = new ArrayList<>();

        try {
            if (javaProjects.isEmpty()) {
                GroovyLanguageServerPlugin.logInfo(
                        "[codeaction] No Java project found for import search");
                return results;
            }

            // Create search scope over all project classpaths
            IJavaSearchScope scope = SearchEngine.createJavaSearchScope(
                    javaProjects.toArray(new IJavaProject[0]), IJavaSearchScope.SOURCES
                            | IJavaSearchScope.APPLICATION_LIBRARIES
                            | IJavaSearchScope.SYSTEM_LIBRARIES
                            | IJavaSearchScope.REFERENCED_PROJECTS);

            // Collect matching type names
            List<TypeNameMatch> matches = new ArrayList<>();
            TypeNameMatchRequestor requestor = new TypeNameMatchRequestor() {
                @Override
                public void acceptTypeNameMatch(TypeNameMatch match) {
                    matches.add(match);
                }
            };

            // Use a progress monitor that checks the thread interrupt flag
            // so SearchEngine can be cancelled when the LSP request times out.
            IProgressMonitor searchMonitor = new IProgressMonitor() {
                private volatile boolean cancelled = false;
                @Override public void beginTask(String name, int totalWork) {}
                @Override public void done() {}
                @Override public void internalWorked(double work) {}
                @Override public boolean isCanceled() {
                    return cancelled || Thread.currentThread().isInterrupted();
                }
                @Override public void setCanceled(boolean value) { cancelled = value; }
                @Override public void setTaskName(String name) {}
                @Override public void subTask(String name) {}
                @Override public void worked(int work) {}
            };

                JdtSearchSupport.searchAllTypeNames(
                    null,                                    // any package
                    SearchPattern.R_EXACT_MATCH,
                    simpleName.toCharArray(),                // type simple name
                    SearchPattern.R_EXACT_MATCH | SearchPattern.R_CASE_SENSITIVE,
                    IJavaSearchConstants.TYPE,               // classes, interfaces, enums
                    scope,
                    requestor,
                    IJavaSearchConstants.FORCE_IMMEDIATE_SEARCH,
                    searchMonitor);

            // Convert matches to FQNs, filtering out internal/synthetic types
            for (TypeNameMatch match : matches) {
                String fqn = match.getFullyQualifiedName();
                if (isImportSearchCandidate(fqn)) {
                    results.add(fqn);
                    if (results.size() >= MAX_IMPORT_SUGGESTIONS) {
                        break;
                    }
                }
            }

            // Sort: prefer shorter package paths (more common types first)
            results.sort((a, b) -> {
                // Prefer types from common packages
                int scoreA = packagePriority(a);
                int scoreB = packagePriority(b);
                if (scoreA != scoreB) return Integer.compare(scoreA, scoreB);
                return a.compareTo(b);
            });

            GroovyLanguageServerPlugin.logInfo(
                    "[codeaction] Search for '" + simpleName + "' found " + results.size() + " candidates");

        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError(
                    "[codeaction] JDT type search failed for '" + simpleName + "'", e);
        }

        importSearchCache.put(projectKey, new CachedSearchResult(results));
        return results;
    }

    private List<IJavaProject> getSearchProjectsForUri(String uri) {
        List<IJavaProject> scopedProjects = new ArrayList<>();
        Set<String> seenProjectNames = new HashSet<>();

        try {
            String normalizedUri = DocumentManager.normalizeUri(uri);
            URI fileUri = toFileLocationUri(normalizedUri);
            if (fileUri == null) {
                throw new IllegalArgumentException("Not a file URI: " + normalizedUri);
            }
            IFile[] files = ResourcesPlugin.getWorkspace().getRoot().findFilesForLocationURI(fileUri);

            for (IFile file : files) {
                IJavaProject javaProject = asSearchProject(file);
                if (javaProject != null && seenProjectNames.add(javaProject.getElementName())) {
                    scopedProjects.add(javaProject);
                }
            }
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logInfo(
                    "[codeaction] Failed to scope import search by URI; falling back to all projects: "
                    + e.getMessage());
        }

        if (!scopedProjects.isEmpty()) {
            return scopedProjects;
        }

        // Fallback when the document cannot be mapped to a workspace project.
        List<IJavaProject> allProjects = new ArrayList<>();
        try {
            for (IProject project : ResourcesPlugin.getWorkspace().getRoot().getProjects()) {
                if (!project.isOpen()) {
                    continue;
                }
                IJavaProject javaProject = JavaCore.create(project);
                if (javaProject != null && javaProject.exists()) {
                    allProjects.add(javaProject);
                }
            }
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logInfo(
                    "[codeaction] Failed to enumerate workspace projects for import search: "
                    + e.getMessage());
        }

        return allProjects;
    }

    /**
     * Assign a priority score to a package for sorting import suggestions.
     * Lower = better (shown first).
     */
    private int packagePriority(String fqn) {
        if (fqn.startsWith("java.lang.")) return 0;
        if (fqn.startsWith("java.util.")) return 1;
        if (fqn.startsWith("java.io.")) return 2;
        if (fqn.startsWith("java.nio.")) return 3;
        if (fqn.startsWith("java.net.")) return 4;
        if (fqn.startsWith("java.")) return 5;
        if (fqn.startsWith("groovy.")) return 6;
        if (fqn.startsWith("javax.") || fqn.startsWith("jakarta.")) return 7;
        if (fqn.startsWith("org.junit.")) return 8;
        if (fqn.startsWith("spock.")) return 8;
        return 10;
    }

    /**
     * Extract a type name from an error message like "unable to resolve class Foo".
     */
    private String extractTypeNameFromMessage(String message) {
        if (message == null) return null;

        // Common patterns from Groovy compiler
        // "unable to resolve class SomeType"
        // "Groovy:unable to resolve class SomeType"
        String marker = "unable to resolve class ";
        int idx = message.indexOf(marker);
        if (idx >= 0) {
            String rest = message.substring(idx + marker.length()).trim();
            // Take the first word (may be qualified)
            int end = 0;
            while (end < rest.length() &&
                    (Character.isJavaIdentifierPart(rest.charAt(end)) || rest.charAt(end) == '.')) {
                end++;
            }
            String fullName = rest.substring(0, end);
            // Return simple name
            int lastDot = fullName.lastIndexOf('.');
            return lastDot >= 0 ? fullName.substring(lastDot + 1) : fullName;
        }

        return null;
    }

    private String getDiagnosticMessage(Diagnostic diagnostic) {
        Object msgObj = diagnostic.getMessage();
        return msgObj != null ? msgObj.toString() : "";
    }

    private boolean isUnresolvedTypeDiagnostic(Diagnostic diagnostic) {
        String code = getDiagnosticCode(diagnostic);
        String message = getDiagnosticMessage(diagnostic);
        return (code != null && code.startsWith(DIAG_CODE_UNRESOLVED_TYPE))
                || message.contains("unable to resolve class")
                || message.contains("Groovy:unable to resolve class");
    }

    // ================================================================
    // Implement missing interface members
    // ================================================================

    private boolean isMissingInterfaceMemberDiagnostic(Diagnostic diagnostic) {
        String message = getDiagnosticMessage(diagnostic);
        if (message == null || message.isEmpty()) {
            return false;
        }

        return (message.contains("must be declared abstract or the method")
                && message.contains("must be implemented"))
                || message.contains("must implement the inherited abstract method");
    }

    private CodeAction createImplementMissingInterfaceMembersAction(String uri, String content,
            Diagnostic diag) {
        try {
            ModuleNode module = documentManager.getGroovyAST(uri);
            if (module == null) {
                return null;
            }

            int targetLine = Math.max(1, diag.getRange().getStart().getLine() + 1);
            ClassNode targetClass = findEnclosingClass(module, targetLine);
            if (targetClass == null) {
                String className = extractClassSimpleNameFromMessage(getDiagnosticMessage(diag));
                targetClass = findClassBySimpleName(module, className);
            }

            if (targetClass == null || targetClass.isInterface()) {
                return null;
            }

            List<MethodNode> missingMethods = findMissingInterfaceMethods(targetClass, module);
            int insertLine = findClassInsertLine(targetClass, content);
            String diagnosticMessage = getDiagnosticMessage(diag);
            String insertionText;
            if (missingMethods.isEmpty()) {
                if (hasConcreteMethodForDiagnosticSignature(targetClass, diagnosticMessage)) {
                    return null;
                }
                insertionText = buildMissingMethodStubFromDiagnostic(
                        targetClass, diagnosticMessage, content, insertLine);
            } else {
                insertionText = buildMissingMethodStubsText(targetClass, missingMethods, content, insertLine);
            }
            if (insertionText.isEmpty()) {
                return null;
            }

            TextEdit insertEdit = new TextEdit(
                    new Range(new Position(insertLine, 0), new Position(insertLine, 0)),
                    insertionText);

            CodeAction action = new CodeAction(
                    missingMethods.size() <= 1
                            ? "Implement inherited abstract member"
                            : "Implement inherited abstract members");
            action.setKind(CodeActionKind.QuickFix);
            action.setDiagnostics(Collections.singletonList(diag));
            action.setIsPreferred(true);

            WorkspaceEdit edit = new WorkspaceEdit();
            edit.setChanges(Collections.singletonMap(uri, Collections.singletonList(insertEdit)));
            action.setEdit(edit);

            return action;
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError("Failed to create implement missing members action", e);
            return null;
        }
    }

    private List<MethodNode> findMissingInterfaceMethods(ClassNode targetClass, ModuleNode currentModule) {
        List<MethodNode> requiredMethods = new ArrayList<>();
        Set<String> requiredSignatures = new TreeSet<>();
        Set<String> visitedInterfaces = new HashSet<>();

        ClassNode[] interfaces = targetClass.getInterfaces();
        if (interfaces == null || interfaces.length == 0) {
            return Collections.emptyList();
        }

        for (ClassNode ifaceRef : interfaces) {
            collectRequiredInterfaceMethodsRecursive(
                    ifaceRef,
                    currentModule,
                    requiredMethods,
                    requiredSignatures,
                    visitedInterfaces);
        }

        collectRequiredSuperclassMethodsRecursive(
                targetClass.getUnresolvedSuperClass(),
                currentModule,
                requiredMethods,
                requiredSignatures);

        List<MethodNode> missingMethods = new ArrayList<>();
        for (MethodNode required : requiredMethods) {
            if (!hasConcreteMethodInHierarchy(targetClass, required)) {
                missingMethods.add(required);
            }
        }

        return missingMethods;
    }

    private void collectRequiredInterfaceMethodsRecursive(ClassNode ifaceRef,
            ModuleNode currentModule,
            List<MethodNode> requiredMethods,
            Set<String> requiredSignatures,
            Set<String> visitedInterfaces) {
        if (ifaceRef == null) {
            return;
        }

        ClassNode resolved = TraitMemberResolver.resolveTraitClassNode(ifaceRef, currentModule, documentManager);
        String interfaceName = resolved.getName();
        if (interfaceName == null || !visitedInterfaces.add(interfaceName)) {
            return;
        }

        for (MethodNode method : resolved.getMethods()) {
            if (!isMethodRequiredForImplementation(method)) {
                continue;
            }
            String signature = methodSignatureKey(method);
            if (requiredSignatures.add(signature)) {
                requiredMethods.add(method);
            }
        }

        ClassNode[] superInterfaces = resolved.getInterfaces();
        if (superInterfaces != null) {
            for (ClassNode superInterface : superInterfaces) {
                collectRequiredInterfaceMethodsRecursive(
                        superInterface,
                        currentModule,
                        requiredMethods,
                        requiredSignatures,
                        visitedInterfaces);
            }
        }
    }

    private void collectRequiredSuperclassMethodsRecursive(ClassNode superClass,
            ModuleNode currentModule,
            List<MethodNode> requiredMethods,
            Set<String> requiredSignatures) {
        if (superClass == null) {
            return;
        }

        superClass = resolveLocalClassReference(superClass, currentModule);

        String superName = superClass.getName();
        if (superName == null
                || "java.lang.Object".equals(superName)
                || "groovy.lang.GroovyObject".equals(superName)) {
            return;
        }

        for (MethodNode method : superClass.getMethods()) {
            if (!isMethodRequiredForImplementation(method)) {
                continue;
            }
            String signature = methodSignatureKey(method);
            if (requiredSignatures.add(signature)) {
                requiredMethods.add(method);
            }
        }

        collectRequiredSuperclassMethodsRecursive(
                superClass.getUnresolvedSuperClass(),
                currentModule,
                requiredMethods,
                requiredSignatures);
    }

    private ClassNode resolveLocalClassReference(ClassNode candidate, ModuleNode currentModule) {
        if (candidate == null || currentModule == null) {
            return candidate;
        }

        String candidateName = candidate.getName();
        if (candidateName == null || candidateName.isEmpty()) {
            return candidate;
        }

        for (ClassNode classNode : currentModule.getClasses()) {
            if (candidateName.equals(classNode.getName())
                    || candidateName.equals(classNode.getNameWithoutPackage())
                    || simpleTypeName(candidateName).equals(classNode.getNameWithoutPackage())) {
                return classNode;
            }
        }
        return candidate;
    }

    private boolean isMethodRequiredForImplementation(MethodNode method) {
        if (method == null) {
            return false;
        }

        String name = method.getName();
        if (name == null || name.isEmpty() || name.startsWith("$")) {
            return false;
        }

        int modifiers = method.getModifiers();
        if (!Modifier.isAbstract(modifiers)
                || Modifier.isStatic(modifiers)
                || Modifier.isPrivate(modifiers)) {
            return false;
        }

        ClassNode declaringClass = method.getDeclaringClass();
        if (declaringClass != null) {
            String declaringName = declaringClass.getName();
            if ("java.lang.Object".equals(declaringName)
                    || "groovy.lang.GroovyObject".equals(declaringName)) {
                return false;
            }
        }

        return true;
    }

    private boolean hasConcreteMethodInHierarchy(ClassNode targetClass, MethodNode requiredMethod) {
        for (ClassNode current = targetClass; current != null; current = current.getSuperClass()) {
            List<MethodNode> candidates = current.getDeclaredMethods(requiredMethod.getName());
            for (MethodNode candidate : candidates) {
                if (hasSameParameterTypes(candidate, requiredMethod)
                        && !Modifier.isAbstract(candidate.getModifiers())) {
                    return true;
                }
            }
        }
        return false;
    }

    private boolean hasSameParameterTypes(MethodNode left, MethodNode right) {
        Parameter[] leftParams = left.getParameters();
        Parameter[] rightParams = right.getParameters();
        if (leftParams == null || rightParams == null) {
            return (leftParams == null || leftParams.length == 0)
                    && (rightParams == null || rightParams.length == 0);
        }
        if (leftParams.length != rightParams.length) {
            return false;
        }

        for (int i = 0; i < leftParams.length; i++) {
            String leftType = normalizeTypeName(leftParams[i].getType());
            String rightType = normalizeTypeName(rightParams[i].getType());
            if (!leftType.equals(rightType)) {
                return false;
            }
        }

        return true;
    }

    private String methodSignatureKey(MethodNode method) {
        StringBuilder sb = new StringBuilder();
        sb.append(method.getName()).append('(');
        Parameter[] parameters = method.getParameters();
        if (parameters != null) {
            for (int i = 0; i < parameters.length; i++) {
                if (i > 0) {
                    sb.append(',');
                }
                sb.append(normalizeTypeName(parameters[i].getType()));
            }
        }
        sb.append(')');
        return sb.toString();
    }

    private String normalizeTypeName(ClassNode type) {
        if (type == null) {
            return "def";
        }
        if (type.isArray()) {
            return normalizeTypeName(type.getComponentType()) + "[]";
        }
        String name = type.getName();
        if (name == null || name.isEmpty()) {
            name = type.getNameWithoutPackage();
        }
        return name == null || name.isEmpty() ? "def" : name;
    }

    private int findClassInsertLine(ClassNode targetClass, String content) {
        String[] lines = content.split("\\n", -1);
        if (lines.length == 0) {
            return 0;
        }

        int startLine = Math.max(0, targetClass.getLineNumber() - 1);
        int endLine = Math.max(startLine, targetClass.getLastLineNumber() - 1);
        endLine = Math.min(endLine, lines.length - 1);

        for (int line = endLine; line >= startLine; line--) {
            if (lines[line].trim().equals("}")) {
                return line;
            }
        }

        return endLine;
    }

    private String buildMissingMethodStubsText(ClassNode targetClass,
            List<MethodNode> missingMethods,
            String content,
            int insertLine) {
        String[] lines = content.split("\\n", -1);
        int classLine = Math.max(0, targetClass.getLineNumber() - 1);

        String classIndent = classLine < lines.length ? leadingWhitespace(lines[classLine]) : "";
        String indentUnit = inferIndentUnit(lines, classIndent, classLine, insertLine);
        String methodIndent = classIndent + indentUnit;
        String bodyIndent = methodIndent + indentUnit;

        StringBuilder sb = new StringBuilder();
        if (insertLine > 0 && insertLine - 1 < lines.length && !lines[insertLine - 1].trim().isEmpty()) {
            sb.append("\n");
        }

        for (int i = 0; i < missingMethods.size(); i++) {
            MethodNode method = missingMethods.get(i);

            sb.append(methodIndent).append("@Override\n");
            sb.append(methodIndent)
                    .append(renderType(method.getReturnType()))
                    .append(' ')
                    .append(method.getName())
                    .append('(')
                    .append(renderParameters(method.getParameters()))
                    .append(") {\n");
            sb.append(bodyIndent)
                    .append("throw new UnsupportedOperationException(\"Method '")
                    .append(method.getName())
                    .append("' is not implemented\")\n");
            sb.append(methodIndent).append("}\n");

            if (i + 1 < missingMethods.size()) {
                sb.append("\n");
            }
        }

        sb.append("\n");
        return sb.toString();
    }

    private String buildMissingMethodStubFromDiagnostic(ClassNode targetClass, String diagnosticMessage,
            String content, int insertLine) {
        String signature = extractMissingMethodSignature(diagnosticMessage);
        if (signature == null || signature.isEmpty()) {
            return "";
        }

        int parenIndex = signature.indexOf('(');
        int closeParenIndex = signature.lastIndexOf(')');
        if (parenIndex <= 0 || closeParenIndex < parenIndex) {
            return "";
        }

        String header = signature.substring(0, parenIndex).trim();
        int lastSpace = header.lastIndexOf(' ');
        String returnType = lastSpace > 0 ? simpleTypeName(header.substring(0, lastSpace).trim()) : "def";
        String methodName = lastSpace > 0 ? header.substring(lastSpace + 1).trim() : header;
        if (!isValidTypeIdentifier(methodName)) {
            return "";
        }

        String params = signature.substring(parenIndex + 1, closeParenIndex).trim();
        List<String> renderedParams = new ArrayList<>();
        if (!params.isEmpty()) {
            String[] pieces = params.split(",");
            for (int i = 0; i < pieces.length; i++) {
                String typeName = pieces[i].trim();
                renderedParams.add(simpleTypeName(typeName) + " arg" + (i + 1));
            }
        }

        String[] lines = content.split("\\n", -1);
        int classLine = Math.max(0, targetClass.getLineNumber() - 1);
        String classIndent = classLine < lines.length ? leadingWhitespace(lines[classLine]) : "";
        String indentUnit = inferIndentUnit(lines, classIndent, classLine, insertLine);
        String methodIndent = classIndent + indentUnit;
        String bodyIndent = methodIndent + indentUnit;

        StringBuilder sb = new StringBuilder();
        if (insertLine > 0 && insertLine - 1 < lines.length && !lines[insertLine - 1].trim().isEmpty()) {
            sb.append("\n");
        }
        sb.append(methodIndent).append("@Override\n");
        sb.append(methodIndent).append(returnType).append(' ').append(methodName).append('(')
                .append(String.join(", ", renderedParams)).append(") {\n");
        sb.append(bodyIndent)
                .append("throw new UnsupportedOperationException(\"Method '")
                .append(methodName)
                .append("' is not implemented\")\n");
        sb.append(methodIndent).append("}\n\n");
        return sb.toString();
    }

    private String extractMissingMethodSignature(String diagnosticMessage) {
        if (diagnosticMessage == null || diagnosticMessage.isEmpty()) {
            return null;
        }

        String marker = "the method '";
        int markerIndex = diagnosticMessage.indexOf(marker);
        if (markerIndex >= 0) {
            int start = markerIndex + marker.length();
            int end = diagnosticMessage.indexOf('\'', start);
            if (end > start) {
                return diagnosticMessage.substring(start, end).trim();
            }
        }

        String inheritedMarker = "must implement the inherited abstract method ";
        int inheritedIndex = diagnosticMessage.indexOf(inheritedMarker);
        if (inheritedIndex >= 0) {
            return diagnosticMessage.substring(inheritedIndex + inheritedMarker.length()).trim();
        }

        return null;
    }

    private boolean hasConcreteMethodForDiagnosticSignature(ClassNode targetClass, String diagnosticMessage) {
        String signature = extractMissingMethodSignature(diagnosticMessage);
        if (signature == null || signature.isEmpty()) {
            return false;
        }

        int parenIndex = signature.indexOf('(');
        int closeParenIndex = signature.lastIndexOf(')');
        if (parenIndex <= 0 || closeParenIndex < parenIndex) {
            return false;
        }

        String header = signature.substring(0, parenIndex).trim();
        int lastSpace = header.lastIndexOf(' ');
        String methodName = lastSpace > 0 ? header.substring(lastSpace + 1).trim() : header;
        String params = signature.substring(parenIndex + 1, closeParenIndex).trim();
        String[] expectedTypes = params.isEmpty() ? new String[0] : params.split(",");

        for (ClassNode current = targetClass; current != null; current = current.getSuperClass()) {
            for (MethodNode candidate : current.getDeclaredMethods(methodName)) {
                if (Modifier.isAbstract(candidate.getModifiers())) {
                    continue;
                }
                Parameter[] candidateParams = candidate.getParameters();
                int candidateLength = candidateParams == null ? 0 : candidateParams.length;
                if (candidateLength != expectedTypes.length) {
                    continue;
                }
                boolean allMatch = true;
                for (int i = 0; i < expectedTypes.length; i++) {
                    String expectedType = expectedTypes[i].trim();
                    String actualType = normalizeTypeName(candidateParams[i].getType());
                    if (!actualType.equals(expectedType)
                            && !simpleTypeName(actualType).equals(simpleTypeName(expectedType))) {
                        allMatch = false;
                        break;
                    }
                }
                if (allMatch) {
                    return true;
                }
            }
        }
        return false;
    }

    private String renderType(ClassNode type) {
        if (type == null) {
            return "def";
        }
        if (type.isArray()) {
            return renderType(type.getComponentType()) + "[]";
        }
        String simpleName = type.getNameWithoutPackage();
        if (simpleName == null || simpleName.isEmpty()) {
            simpleName = type.getName();
        }
        return simpleName == null || simpleName.isEmpty() ? "def" : simpleName;
    }

    private String renderParameters(Parameter[] parameters) {
        if (parameters == null || parameters.length == 0) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < parameters.length; i++) {
            if (i > 0) {
                sb.append(", ");
            }
            Parameter parameter = parameters[i];
            String name = sanitizeParameterName(parameter.getName(), i + 1);
            sb.append(renderType(parameter.getType())).append(' ').append(name);
        }
        return sb.toString();
    }

    private String sanitizeParameterName(String rawName, int position) {
        if (rawName == null || rawName.isEmpty()) {
            return "arg" + position;
        }
        if (!Character.isJavaIdentifierStart(rawName.charAt(0))) {
            return "arg" + position;
        }
        for (int i = 1; i < rawName.length(); i++) {
            if (!Character.isJavaIdentifierPart(rawName.charAt(i))) {
                return "arg" + position;
            }
        }
        return rawName;
    }

    private String inferIndentUnit(String[] lines, String classIndent, int classLine, int insertLine) {
        int start = Math.max(0, classLine + 1);
        int end = Math.min(lines.length - 1, Math.max(classLine, insertLine));

        for (int i = start; i <= end; i++) {
            String line = lines[i];
            if (line.trim().isEmpty()) {
                continue;
            }

            String indent = leadingWhitespace(line);
            if (indent.length() > classIndent.length() && indent.startsWith(classIndent)) {
                String delta = indent.substring(classIndent.length());
                if (!delta.isEmpty()) {
                    return delta;
                }
            }
        }

        return "    ";
    }

    private String leadingWhitespace(String line) {
        int i = 0;
        while (i < line.length()) {
            char c = line.charAt(i);
            if (c != ' ' && c != '\t') {
                break;
            }
            i++;
        }
        return line.substring(0, i);
    }

    private ClassNode findEnclosingClass(ModuleNode module, int targetLine) {
        ClassNode best = null;
        for (ClassNode classNode : module.getClasses()) {
            int start = classNode.getLineNumber();
            int end = classNode.getLastLineNumber();
            boolean enclosesTarget = start > 0 && end >= start
                    && targetLine >= start && targetLine <= end;
            boolean declaredBeforeTarget = start > 0 && start <= targetLine;
            if ((enclosesTarget || declaredBeforeTarget)
                    && (best == null || start >= best.getLineNumber())) {
                best = classNode;
            }
        }
        return best;
    }

    private ClassNode findClassBySimpleName(ModuleNode module, String simpleName) {
        if (simpleName == null || simpleName.isEmpty()) {
            return null;
        }
        for (ClassNode classNode : module.getClasses()) {
            if (simpleName.equals(classNode.getNameWithoutPackage())) {
                return classNode;
            }
        }
        return null;
    }

    private String extractClassSimpleNameFromMessage(String message) {
        if (message == null || message.isEmpty()) {
            return null;
        }

        String quotedCandidate = extractQuotedTypeCandidate(message);
        if (quotedCandidate != null) {
            return simpleTypeName(quotedCandidate);
        }

        String markerCandidate = extractTypeCandidateAfterMarker(message, TYPE_MESSAGE_MARKER);
        if (markerCandidate != null) {
            return simpleTypeName(markerCandidate);
        }

        return null;
    }

    /**
     * Get the set of fully qualified names already imported in a document.
     */
    private Set<String> getExistingImports(String uri) {
        Set<String> imports = new TreeSet<>();
        ModuleNode ast = documentManager.getGroovyAST(uri);
        if (ast != null) {
            for (ImportNode imp : ast.getImports()) {
                if (imp.getType() != null) {
                    imports.add(imp.getType().getName());
                }
            }
        }
        return imports;
    }

    /**
     * Find the line number where new imports should be inserted.
     * Returns the line after the last import statement, or after the package
     * declaration, or line 0 if neither exists.
     */
    private int findImportInsertLine(String content) {
        String[] lines = content.split("\n", -1);
        int lastImportLine = -1;
        int packageLine = -1;

        for (int i = 0; i < lines.length; i++) {
            String trimmed = lines[i].trim();
            if (trimmed.startsWith("package ")) {
                packageLine = i;
            }
            if (trimmed.startsWith(IMPORT_PREFIX)) {
                lastImportLine = i;
            }
            // Stop scanning after first class/interface/enum/trait/def
            if (trimmed.startsWith("class ") || trimmed.startsWith("interface ")
                    || trimmed.startsWith("enum ") || trimmed.startsWith("trait ")
                    || trimmed.startsWith("@") || trimmed.startsWith("def ")
                    || trimmed.startsWith("public ") || trimmed.startsWith("abstract ")
                    || trimmed.startsWith("final ")) {
                break;
            }
        }

        if (lastImportLine >= 0) {
            return lastImportLine + 1;
        }
        if (packageLine >= 0) {
            return packageLine + 2; // blank line after package
        }
        return 0;
    }

    // ================================================================
    // Organize imports
    // ================================================================

    private CodeAction createOrganizeImportsAction(String uri, String content,
            List<Diagnostic> diagnostics, List<String> onlyKinds) {
        if (!wantsKind(onlyKinds, CodeActionKind.Source, CodeActionKind.SourceOrganizeImports)) {
            return null;
        }

        TextEdit edit = createOrganizeImportsEdit(uri, content, diagnostics);
        if (edit == null) {
            return null;
        }

        CodeAction action = new CodeAction("Organize imports");
        action.setKind(CodeActionKind.SourceOrganizeImports);

        WorkspaceEdit workspaceEdit = new WorkspaceEdit();
        workspaceEdit.setChanges(Collections.singletonMap(uri, Collections.singletonList(edit)));
        action.setEdit(workspaceEdit);

        return action;
    }

    private CodeAction createRemoveAllUnusedImportsAction(String uri, String content, List<String> onlyKinds) {
        if (!wantsKind(onlyKinds, CodeActionKind.Source, SOURCE_KIND_REMOVE_UNUSED_IMPORTS)) {
            return null;
        }

        List<TextEdit> edits = createRemoveUnusedImportEdits(uri, content);
        if (edits.isEmpty()) {
            return null;
        }

        CodeAction action = new CodeAction("Remove all unused imports");
        action.setKind(SOURCE_KIND_REMOVE_UNUSED_IMPORTS);

        WorkspaceEdit edit = new WorkspaceEdit();
        edit.setChanges(Collections.singletonMap(uri, edits));
        action.setEdit(edit);

        return action;
    }

    private CodeAction createRemoveAllUnusedImportsQuickFixAction(String uri, String content,
            List<Diagnostic> diagnostics) {
        List<TextEdit> edits = createRemoveUnusedImportEdits(uri, content);
        if (edits.isEmpty()) {
            return null;
        }

        CodeAction action = new CodeAction("Remove all unused imports");
        action.setKind(CodeActionKind.QuickFix);
        if (diagnostics != null && !diagnostics.isEmpty()) {
            action.setDiagnostics(diagnostics);
        }

        WorkspaceEdit edit = new WorkspaceEdit();
        edit.setChanges(Collections.singletonMap(uri, edits));
        action.setEdit(edit);

        return action;
    }

    private CodeAction createAddAllMissingImportsQuickFixAction(String uri, String content,
            List<Diagnostic> diagnostics) {
        try {
            MissingImportsResult missingImports =
                    collectMissingImports(uri, diagnostics, getExistingImports(uri));

            if (missingImports.importsToAdd.size() < 2) {
                return null;
            }

            TextEdit insertEdit = createAddImportsEdit(content, missingImports.importsToAdd);

            CodeAction action = new CodeAction("Add all missing imports");
            action.setKind(CodeActionKind.QuickFix);
            action.setDiagnostics(missingImports.matchedDiagnostics);

            WorkspaceEdit edit = new WorkspaceEdit();
            edit.setChanges(Collections.singletonMap(uri, Collections.singletonList(insertEdit)));
            action.setEdit(edit);

            return action;
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError("Failed to create add all missing imports quick fix action", e);
            return null;
        }
    }

    private CodeAction createFixAllAction(String uri, String content,
            List<Diagnostic> diagnostics, List<String> onlyKinds) {
        if (!wantsKind(onlyKinds, CodeActionKind.Source, CodeActionKind.SourceFixAll, SOURCE_KIND_FIX_ALL_GROOVY)) {
            return null;
        }

        List<TextEdit> edits = new ArrayList<>();
        TextEdit organizeImportsEdit = createOrganizeImportsEdit(uri, content, diagnostics);
        if (organizeImportsEdit != null) {
            edits.add(organizeImportsEdit);
        }
        edits.addAll(createDeleteUnusedDeclarationEdits(uri, content, diagnostics));
        if (edits.isEmpty()) {
            return null;
        }

        CodeAction action = new CodeAction("Fix all auto-fixable issues");
        action.setKind(getFixAllActionKind(onlyKinds));
        action.setDiagnostics(diagnostics);

        WorkspaceEdit edit = new WorkspaceEdit();
        edit.setChanges(Collections.singletonMap(uri, edits));
        action.setEdit(edit);
        return action;
    }

    private String getFixAllActionKind(List<String> onlyKinds) {
        if (onlyKinds != null
                && onlyKinds.contains(SOURCE_KIND_FIX_ALL_GROOVY)
                && !onlyKinds.contains(CodeActionKind.SourceFixAll)) {
            return SOURCE_KIND_FIX_ALL_GROOVY;
        }
        return CodeActionKind.SourceFixAll;
    }

    private List<TextEdit> createRemoveUnusedImportEdits(String uri, String content) {
        ModuleNode ast = documentManager.getGroovyAST(uri);
        if (ast == null) return Collections.emptyList();

        Set<String> unusedImportLines = UnusedImportDetector.findUnusedImportLines(ast, content);
        if (unusedImportLines.isEmpty()) return Collections.emptyList();

        List<TextEdit> edits = new ArrayList<>();
        String[] lines = content.split("\n", -1);

        for (int i = lines.length - 1; i >= 0; i--) {
            String trimmed = lines[i].trim();
            if (unusedImportLines.contains(trimmed)) {
                edits.add(new TextEdit(
                        new Range(new Position(i, 0), new Position(i + 1, 0)),
                        ""));
            }
        }

        return edits;
    }

    private TextEdit createOrganizeImportsEdit(String uri, String content, List<Diagnostic> diagnostics) {
        OrganizedImportsResult organized = organizeImports(uri, content, diagnostics);
        if (organized == null || !organized.changed) {
            return null;
        }
        return new TextEdit(organized.range, organized.replacementText);
    }

    private OrganizedImportsResult organizeImports(String uri, String content, List<Diagnostic> diagnostics) {
        String[] lines = content.split("\n", -1);
        int firstImportLine = -1;
        int lastImportLine = -1;
        List<String> preservedImportBlockLines = new ArrayList<>();
        Set<String> regularImports = new TreeSet<>((left, right) -> {
            int score = Integer.compare(packagePriority(left), packagePriority(right));
            return score != 0 ? score : left.compareTo(right);
        });
        int regularImportInsertIndex = -1;

        Set<String> unusedImportLines = Collections.emptySet();
        ModuleNode ast = documentManager.getGroovyAST(uri);
        if (ast != null) {
            unusedImportLines = UnusedImportDetector.findUnusedImportLines(ast, content);
        }

        for (int i = 0; i < lines.length; i++) {
            String trimmed = lines[i].trim();
            if (!trimmed.startsWith(IMPORT_PREFIX)) {
                continue;
            }

            if (firstImportLine < 0) {
                firstImportLine = i;
            }
            lastImportLine = i;

            if (unusedImportLines.contains(trimmed)) {
                continue;
            }

            Matcher simpleImportMatcher = SIMPLE_IMPORT_PATTERN.matcher(trimmed);
            if (trimmed.startsWith("import static ") || !simpleImportMatcher.matches()) {
                preservedImportBlockLines.add(lines[i]);
                continue;
            }

            String importedName = simpleImportMatcher.group(1);
            if (importedName.endsWith(".*") || trimmed.contains(" as ")) {
                preservedImportBlockLines.add(lines[i]);
                continue;
            }

            if (regularImportInsertIndex < 0) {
                regularImportInsertIndex = preservedImportBlockLines.size();
            }
            regularImports.add(importedName);
        }

        MissingImportsResult missingImports =
                collectMissingImports(uri, diagnostics, new HashSet<>(regularImports));
        regularImports.addAll(missingImports.importsToAdd);

        int endLineExclusive = lastImportLine >= 0 ? lastImportLine + 1 : 0;
        while (endLineExclusive < lines.length && lines[endLineExclusive].trim().isEmpty()) {
            endLineExclusive++;
        }

        if (firstImportLine >= 0) {
            preserveInterleavedImportComments(lines, firstImportLine, endLineExclusive, preservedImportBlockLines);
        }

        String replacement = buildOrganizedImportBlock(
                regularImports,
                preservedImportBlockLines,
                regularImportInsertIndex,
                firstImportLine >= 0 || !regularImports.isEmpty() || !preservedImportBlockLines.isEmpty());
        if (firstImportLine < 0) {
            if (replacement.isEmpty()) {
                return null;
            }
            int insertLine = findImportInsertLine(content);
            Range insertRange = new Range(new Position(insertLine, 0), new Position(insertLine, 0));
            return new OrganizedImportsResult(insertRange, replacement, true);
        }

        Range replaceRange = new Range(new Position(firstImportLine, 0), new Position(endLineExclusive, 0));
        String existingBlock = sliceLines(lines, firstImportLine, endLineExclusive);
        boolean changed = !existingBlock.equals(replacement);
        return new OrganizedImportsResult(replaceRange, replacement, changed);
    }

    private void preserveInterleavedImportComments(String[] lines, int startLine, int endLineExclusive,
            List<String> preservedImportBlockLines) {
        for (int i = startLine; i < endLineExclusive; i++) {
            String trimmed = lines[i].trim();
            if (!trimmed.isEmpty() && !trimmed.startsWith(IMPORT_PREFIX)) {
                preservedImportBlockLines.add(lines[i]);
            }
        }
    }

    private String buildOrganizedImportBlock(Set<String> regularImports,
            List<String> preservedImportBlockLines, int regularImportInsertIndex,
            boolean includeTrailingBlankLine) {
        List<String> organizedLines = new ArrayList<>(preservedImportBlockLines);
        List<String> regularImportLines = new ArrayList<>();
        for (String importName : regularImports) {
            regularImportLines.add(IMPORT_PREFIX + importName);
        }
        int insertIndex = regularImportInsertIndex >= 0 ? regularImportInsertIndex : 0;
        organizedLines.addAll(insertIndex, regularImportLines);

        while (!organizedLines.isEmpty() && organizedLines.get(organizedLines.size() - 1).trim().isEmpty()) {
            organizedLines.remove(organizedLines.size() - 1);
        }

        StringBuilder sb = new StringBuilder();
        for (String line : organizedLines) {
            sb.append(line).append(LINE_SEPARATOR);
        }
        if (!organizedLines.isEmpty() && includeTrailingBlankLine) {
            sb.append(LINE_SEPARATOR);
        }
        return sb.toString();
    }

    private TextEdit createAddImportsEdit(String content, Set<String> importsToAdd) {
        int insertLine = findImportInsertLine(content);
        String importBlock = buildImportBlock(importsToAdd);
        return new TextEdit(
                new Range(new Position(insertLine, 0), new Position(insertLine, 0)),
                importBlock);
    }

    private List<TextEdit> createDeleteUnusedDeclarationEdits(String uri, String content,
            List<Diagnostic> diagnostics) {
        List<TextEdit> edits = new ArrayList<>();
        if (diagnostics == null || diagnostics.isEmpty()) {
            return edits;
        }

        for (Diagnostic diagnostic : diagnostics) {
            if (!DIAG_CODE_UNUSED_DECLARATION.equals(getDiagnosticCode(diagnostic))) {
                continue;
            }
            Range range = findUnusedDeclarationRangeSafely(uri, content, diagnostic);
            if (range != null) {
                edits.add(new TextEdit(range, ""));
            }
        }

        edits.sort((left, right) -> compareRanges(left.getRange(), right.getRange()));
        List<TextEdit> filtered = new ArrayList<>();
        for (TextEdit edit : edits) {
            if (filtered.isEmpty()) {
                filtered.add(edit);
                continue;
            }
            Range previousRange = filtered.get(filtered.size() - 1).getRange();
            if (intersects(previousRange, edit.getRange())) {
                continue;
            }
            filtered.add(edit);
        }
        return filtered;
    }

    private IJavaProject asSearchProject(IFile file) {
        IProject project = file.getProject();
        if (project == null || !project.isOpen()) {
            return null;
        }

        IJavaProject javaProject = JavaCore.create(project);
        if (javaProject == null || !javaProject.exists()) {
            return null;
        }
        return javaProject;
    }

    private boolean isImportSearchCandidate(String fqn) {
        if (fqn == null || fqn.isEmpty()) {
            return false;
        }
        if (fqn.contains("$")) {
            return false;
        }
        return !fqn.startsWith("sun.")
                && !fqn.startsWith("com.sun.")
                && !fqn.startsWith("jdk.internal.");
    }

    private MissingImportsResult collectMissingImports(String uri,
            List<Diagnostic> diagnostics,
            Set<String> existingImports) {
        Set<String> importsToAdd = new TreeSet<>();
        List<Diagnostic> matchedDiagnostics = new ArrayList<>();

        for (Diagnostic diag : diagnostics) {
            String candidate = resolveMissingImportCandidate(uri, diag, existingImports, importsToAdd);
            if (candidate != null) {
                importsToAdd.add(candidate);
                matchedDiagnostics.add(diag);
            }
        }

        return new MissingImportsResult(importsToAdd, matchedDiagnostics);
    }

    private String resolveMissingImportCandidate(String uri,
            Diagnostic diag,
            Set<String> existingImports,
            Set<String> importsToAdd) {
        if (!isUnresolvedTypeDiagnostic(diag)) {
            return null;
        }

        String typeName = extractTypeNameFromMessage(getDiagnosticMessage(diag));
        if (typeName == null || typeName.isEmpty()) {
            return null;
        }

        List<String> candidates = searchClasspathForType(typeName, uri);
        for (String candidate : candidates) {
            if (!existingImports.contains(candidate) && !importsToAdd.contains(candidate)) {
                return candidate;
            }
        }
        return null;
    }

    private String buildImportBlock(Set<String> importsToAdd) {
        StringBuilder importBlock = new StringBuilder();
        for (String fqn : importsToAdd) {
            importBlock.append(IMPORT_PREFIX).append(fqn).append(LINE_SEPARATOR);
        }
        return importBlock.toString();
    }

    private Range findUnusedDeclarationRangeSafely(String uri, String content, Diagnostic diag) {
        try {
            return findUnusedDeclarationRange(uri, content, diag);
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError("Failed to resolve unused declaration range", e);
            return null;
        }
    }

    private boolean isUnusedMethodDiagnostic(Diagnostic diag) {
        String message = getDiagnosticMessage(diag);
        return message.contains("method '") && message.contains(" is never used");
    }

    private int compareRanges(Range left, Range right) {
        int startCompare = comparePositions(left.getStart(), right.getStart());
        if (startCompare != 0) {
            return startCompare;
        }
        return comparePositions(right.getEnd(), left.getEnd());
    }

    private int comparePositions(Position left, Position right) {
        int lineCompare = Integer.compare(left.getLine(), right.getLine());
        if (lineCompare != 0) {
            return lineCompare;
        }
        return Integer.compare(left.getCharacter(), right.getCharacter());
    }

    private boolean intersects(Range left, Range right) {
        if (left == null || right == null) {
            return false;
        }
        if (comparePositions(left.getStart(), left.getEnd()) == 0) {
            return containsPosition(right, left.getStart());
        }
        if (comparePositions(right.getStart(), right.getEnd()) == 0) {
            return containsPosition(left, right.getStart());
        }
        return comparePositions(left.getStart(), right.getEnd()) < 0
                && comparePositions(right.getStart(), left.getEnd()) < 0;
    }

    private boolean containsPosition(Range range, Position position) {
        return comparePositions(range.getStart(), position) <= 0
                && comparePositions(position, range.getEnd()) <= 0;
    }

    private String sliceLines(String[] lines, int startInclusive, int endExclusive) {
        StringBuilder sb = new StringBuilder();
        for (int i = startInclusive; i < endExclusive; i++) {
            sb.append(lines[i]);
            if (i + 1 < endExclusive || endExclusive < lines.length) {
                sb.append(LINE_SEPARATOR);
            }
        }
        return sb.toString();
    }

    private String extractUnresolvedTypeCandidate(String message) {
        if (message == null || message.isEmpty()) {
            return null;
        }
        String marker = "unable to resolve class ";
        int idx = message.indexOf(marker);
        if (idx < 0) {
            return null;
        }

        String rest = message.substring(idx + marker.length()).trim();
        int end = 0;
        while (end < rest.length()
                && (Character.isJavaIdentifierPart(rest.charAt(end)) || rest.charAt(end) == '.')) {
            end++;
        }
        return end == 0 ? null : rest.substring(0, end);
    }

    private String getCurrentPackageName(String content) {
        if (content == null || content.isEmpty()) {
            return "";
        }
        Matcher matcher = PACKAGE_DECLARATION_PATTERN.matcher(content);
        if (!matcher.find()) {
            return "";
        }
        String pkg = matcher.group(1);
        return pkg == null ? "" : pkg.trim();
    }

    private boolean isValidTypeIdentifier(String candidate) {
        if (candidate == null || candidate.isEmpty()) {
            return false;
        }
        if (!Character.isJavaIdentifierStart(candidate.charAt(0))) {
            return false;
        }
        for (int i = 1; i < candidate.length(); i++) {
            if (!Character.isJavaIdentifierPart(candidate.charAt(i))) {
                return false;
            }
        }
        return true;
    }

    private Path resolveNewTypePath(String currentUri, String currentPackage, String targetPackage,
            String simpleName) {
        Path currentPath = toFilePath(DocumentManager.normalizeUri(currentUri));
        if (currentPath == null) {
            return null;
        }
        try {
            Path currentParent = currentPath.getParent();
            if (currentParent == null) {
                return null;
            }

            Path sourceRoot = resolveSourceRoot(currentParent, currentPackage);
            if (sourceRoot == null) {
                sourceRoot = currentParent;
            }

            Path targetDir = sourceRoot;
            if (targetPackage != null && !targetPackage.isBlank()) {
                for (String segment : targetPackage.split("\\.")) {
                    if (!segment.isEmpty()) {
                        targetDir = targetDir.resolve(segment);
                    }
                }
            }
            return targetDir.resolve(simpleName + ".groovy");
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logInfo(
                    "[codeaction] Failed to resolve new type path for " + currentUri + ": " + e.getMessage());
            return null;
        }
    }

    private URI toFileLocationUri(String uri) {
        if (uri == null || uri.isBlank()) {
            return null;
        }
        try {
            URI parsed = URI.create(uri);
            return "file".equals(parsed.getScheme()) ? parsed : null;
        } catch (Exception e) {
            return null;
        }
    }

    private Path toFilePath(String uri) {
        URI fileUri = toFileLocationUri(uri);
        if (fileUri == null) {
            return null;
        }
        try {
            return Paths.get(fileUri);
        } catch (Exception e) {
            return null;
        }
    }

    private Path resolveSourceRoot(Path currentParent, String currentPackage) {
        String normalizedParent = currentParent.toString().replace('\\', '/');
        for (String rootSegment : SOURCE_ROOT_SEGMENTS) {
            int idx = normalizedParent.indexOf(rootSegment);
            if (idx >= 0) {
                return Paths.get(normalizedParent.substring(0, idx + rootSegment.length() - 1));
            }
            String withoutTrailingSlash = rootSegment.substring(0, rootSegment.length() - 1);
            if (normalizedParent.endsWith(withoutTrailingSlash)) {
                return currentParent;
            }
        }

        if (currentPackage == null || currentPackage.isBlank()) {
            return currentParent;
        }

        String[] segments = currentPackage.split("\\.");
        Path sourceRoot = currentParent;
        for (int i = 0; i < segments.length && sourceRoot != null; i++) {
            sourceRoot = sourceRoot.getParent();
        }
        return sourceRoot;
    }

    private String extractQuotedTypeCandidate(String message) {
        int firstQuote = message.indexOf('\'');
        if (firstQuote < 0) {
            return null;
        }

        int secondQuote = message.indexOf('\'', firstQuote + 1);
        if (secondQuote <= firstQuote + 1) {
            return null;
        }

        return message.substring(firstQuote + 1, secondQuote).trim();
    }

    private String extractTypeCandidateAfterMarker(String message, String marker) {
        int markerIndex = message.indexOf(marker);
        if (markerIndex < 0) {
            return null;
        }

        String rest = message.substring(markerIndex + marker.length()).trim();
        int end = 0;
        while (end < rest.length()
                && (Character.isJavaIdentifierPart(rest.charAt(end)) || rest.charAt(end) == '.')) {
            end++;
        }

        if (end == 0) {
            return null;
        }
        return rest.substring(0, end);
    }

    private String simpleTypeName(String fqnOrSimple) {
        int dot = fqnOrSimple.lastIndexOf('.');
        return dot >= 0 ? fqnOrSimple.substring(dot + 1) : fqnOrSimple;
    }

    private static final class CodeActionRequest {
        private final String uri;
        private final String content;
        private final Range range;
        private final List<String> onlyKinds;
        private final List<Diagnostic> requestDiagnostics;
        private final List<Diagnostic> allDiagnostics;
        private final boolean wantQuickfix;
        private final boolean wantSource;

        private CodeActionRequest(String uri,
                String content,
                Range range,
                List<String> onlyKinds,
                List<Diagnostic> requestDiagnostics,
                List<Diagnostic> allDiagnostics,
                boolean wantQuickfix,
                boolean wantSource) {
            this.uri = uri;
            this.content = content;
            this.range = range;
            this.onlyKinds = onlyKinds;
            this.requestDiagnostics = requestDiagnostics;
            this.allDiagnostics = allDiagnostics;
            this.wantQuickfix = wantQuickfix;
            this.wantSource = wantSource;
        }
    }

    private static final class MissingImportsResult {
        private final Set<String> importsToAdd;
        private final List<Diagnostic> matchedDiagnostics;

        private MissingImportsResult(Set<String> importsToAdd,
                List<Diagnostic> matchedDiagnostics) {
            this.importsToAdd = importsToAdd;
            this.matchedDiagnostics = matchedDiagnostics;
        }
    }

    private static final class OrganizedImportsResult {
        private final Range range;
        private final String replacementText;
        private final boolean changed;

        private OrganizedImportsResult(Range range, String replacementText, boolean changed) {
            this.range = range;
            this.replacementText = replacementText;
            this.changed = changed;
        }
    }

    private boolean wantsKind(List<String> onlyKinds, String... expectedKinds) {
        if (onlyKinds == null) {
            return true;
        }

        for (String expectedKind : expectedKinds) {
            if (onlyKinds.contains(expectedKind)) {
                return true;
            }
        }

        return false;
    }
}
