/*******************************************************************************
 * Copyright (c) 2026 Groovy Language Server Contributors.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
package org.eclipse.groovy.ls.core.providers;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.net.URI;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.lang.reflect.Modifier;

import org.codehaus.groovy.ast.ClassNode;
import org.codehaus.groovy.ast.ImportNode;
import org.codehaus.groovy.ast.MethodNode;
import org.codehaus.groovy.ast.ModuleNode;
import org.codehaus.groovy.ast.Parameter;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.groovy.ls.core.DocumentManager;
import org.eclipse.groovy.ls.core.GroovyLanguageServerPlugin;
import org.eclipse.jdt.core.IJavaProject;
import org.eclipse.jdt.core.JavaCore;
import org.eclipse.jdt.core.search.IJavaSearchConstants;
import org.eclipse.jdt.core.search.IJavaSearchScope;
import org.eclipse.jdt.core.search.SearchEngine;
import org.eclipse.jdt.core.search.SearchPattern;
import org.eclipse.jdt.core.search.TypeNameMatch;
import org.eclipse.jdt.core.search.TypeNameMatchRequestor;
import org.eclipse.lsp4j.*;
import org.eclipse.lsp4j.jsonrpc.messages.Either;

/**
 * Provides LSP code actions for Groovy documents.
 * <p>
 * Supported actions:
 * <ul>
 *   <li><b>Remove unused import</b> — triggered from unused import warnings</li>
 *   <li><b>Organize imports</b> — removes all unused imports at once</li>
 *   <li><b>Add import</b> — suggests imports for unresolved type references
 *       (searches the JDT classpath index for matching types)</li>
 * </ul>
 */
public class CodeActionProvider {

    /** Diagnostic code for unused imports (generated by our DiagnosticsProvider). */
    public static final String DIAG_CODE_UNUSED_IMPORT = "groovy.unusedImport";
    /** Diagnostic code prefix for unresolved types. */
    public static final String DIAG_CODE_UNRESOLVED_TYPE = "groovy.unresolvedType";
    /** Source action kind for adding all missing imports. */
    public static final String SOURCE_KIND_ADD_MISSING_IMPORTS = "source.addMissingImports";
    /** Source action kind for removing all unused imports. */
    public static final String SOURCE_KIND_REMOVE_UNUSED_IMPORTS = "source.removeUnusedImports";

    /** Maximum number of import suggestions to return per unresolved type. */
    private static final int MAX_IMPORT_SUGGESTIONS = 10;

    private final DocumentManager documentManager;
    private final DiagnosticsProvider diagnosticsProvider;

    public CodeActionProvider(DocumentManager documentManager,
            DiagnosticsProvider diagnosticsProvider) {
        this.documentManager = documentManager;
        this.diagnosticsProvider = diagnosticsProvider;
    }

    private static String getDiagnosticCode(Diagnostic diag) {
        if (diag.getCode() == null) return null;
        if (diag.getCode().isLeft()) return diag.getCode().getLeft();
        if (diag.getCode().isRight()) return String.valueOf(diag.getCode().getRight());
        return null;
    }

    /**
     * Compute code actions for the given request.
     */
    public List<Either<Command, CodeAction>> getCodeActions(CodeActionParams params) {
        String uri = params.getTextDocument().getUri();
        List<Diagnostic> diagnostics = params.getContext().getDiagnostics();
        if (diagnostics == null) {
            diagnostics = new ArrayList<>();
        }
        List<Either<Command, CodeAction>> actions = new ArrayList<>();

        String content = documentManager.getContent(uri);
        if (content == null) {
            return actions;
        }

        // Collect action types requested by the client
        List<String> onlyKinds = null;
        if (params.getContext().getOnly() != null) {
            onlyKinds = params.getContext().getOnly();
        }

        boolean wantQuickfix = onlyKinds == null || onlyKinds.contains(CodeActionKind.QuickFix);
        boolean wantSource = onlyKinds == null || onlyKinds.contains(CodeActionKind.Source)
            || onlyKinds.contains(CodeActionKind.SourceOrganizeImports)
            || onlyKinds.contains(SOURCE_KIND_ADD_MISSING_IMPORTS)
            || onlyKinds.contains(SOURCE_KIND_REMOVE_UNUSED_IMPORTS);

        // Some clients send an empty diagnostics list for source actions or broad
        // quick-fix requests. Fall back to the latest/captured document diagnostics.
        if ((wantSource || wantQuickfix) && diagnostics.isEmpty()) {
            diagnostics = diagnosticsProvider.getLatestDiagnostics(uri);
            if (diagnostics.isEmpty()) {
                diagnostics = diagnosticsProvider.collectDiagnosticsForCodeActions(uri);
            }
        }

        // "All missing imports" must always operate on full-document diagnostics,
        // not only the diagnostics attached to the current cursor range.
        List<Diagnostic> allDiagnostics = diagnosticsProvider.getLatestDiagnostics(uri);
        if (allDiagnostics.isEmpty()) {
            allDiagnostics = diagnosticsProvider.collectDiagnosticsForCodeActions(uri);
        }

        if (wantQuickfix) {
            for (Diagnostic diag : diagnostics) {
                String code = getDiagnosticCode(diag);
                // Remove unused import
                if (DIAG_CODE_UNUSED_IMPORT.equals(code)) {
                    CodeAction removeAction = createRemoveImportAction(uri, content, diag);
                    if (removeAction != null) {
                        actions.add(Either.forRight(removeAction));
                    }
                }

                // Add import for unresolved type — match on code OR message text
                if (isUnresolvedTypeDiagnostic(diag)) {
                    List<CodeAction> importActions = createAddImportActions(uri, content, diag);
                    for (CodeAction a : importActions) {
                        actions.add(Either.forRight(a));
                    }
                }

                // Implement missing interface members
                if (isMissingInterfaceMemberDiagnostic(diag)) {
                    CodeAction implementAction = createImplementMissingInterfaceMembersAction(uri, content, diag);
                    if (implementAction != null) {
                        actions.add(Either.forRight(implementAction));
                    }
                }
            }

            // Surface bulk quick-fix actions whenever quick fixes are requested.
            CodeAction removeAllUnusedImportsQuickFix =
                    createRemoveAllUnusedImportsQuickFixAction(uri, content, diagnostics);
            if (removeAllUnusedImportsQuickFix != null) {
                actions.add(Either.forRight(removeAllUnusedImportsQuickFix));
            }

            CodeAction addAllMissingImportsQuickFix =
                    createAddAllMissingImportsQuickFixAction(uri, content, allDiagnostics);
            if (addAllMissingImportsQuickFix != null) {
                actions.add(Either.forRight(addAllMissingImportsQuickFix));
            }
        }

        if (wantSource) {
            // "Organize imports" — removes all unused imports
            CodeAction organizeImports = createOrganizeImportsAction(uri, content, onlyKinds);
            if (organizeImports != null) {
                actions.add(Either.forRight(organizeImports));
            }

            CodeAction removeAllUnusedImports = createRemoveAllUnusedImportsAction(uri, content, onlyKinds);
            if (removeAllUnusedImports != null) {
                actions.add(Either.forRight(removeAllUnusedImports));
            }

            CodeAction addAllMissingImports = createAddAllMissingImportsAction(uri, content, allDiagnostics, onlyKinds);
            if (addAllMissingImports != null) {
                actions.add(Either.forRight(addAllMissingImports));
            }
        }

        return actions;
    }

    // ================================================================
    // Remove unused import
    // ================================================================

    private CodeAction createRemoveImportAction(String uri, String content, Diagnostic diag) {
        try {
            Range importRange = diag.getRange();
            // Expand to full line (including the newline)
            int startLine = importRange.getStart().getLine();
            String[] lines = content.split("\n", -1);
            if (startLine < 0 || startLine >= lines.length) return null;

            Range fullLineRange = new Range(
                    new Position(startLine, 0),
                    new Position(startLine + 1, 0));

            TextEdit removeEdit = new TextEdit(fullLineRange, "");

            CodeAction action = new CodeAction("Remove unused import");
            action.setKind(CodeActionKind.QuickFix);
            action.setDiagnostics(Collections.singletonList(diag));
            action.setIsPreferred(true);

            WorkspaceEdit edit = new WorkspaceEdit();
            edit.setChanges(Collections.singletonMap(uri, Collections.singletonList(removeEdit)));
            action.setEdit(edit);

            return action;
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError("Failed to create remove import action", e);
            return null;
        }
    }

    // ================================================================
    // Add import for unresolved type
    // ================================================================

    private List<CodeAction> createAddImportActions(String uri, String content, Diagnostic diag) {
        List<CodeAction> actions = new ArrayList<>();

        try {
            // Extract the type name from the diagnostic message
            // getMessage() may return String or Either<String,MarkupContent> depending on lsp4j version
            Object msgObj = diag.getMessage();
            String message = msgObj != null ? msgObj.toString() : null;
            String typeName = extractTypeNameFromMessage(message);
            if (typeName == null || typeName.isEmpty()) return actions;

            // Search the JDT classpath index for matching types
            List<String> candidates = searchClasspathForType(typeName, uri);

            // Also check imports already present to avoid duplicates
            Set<String> existingImports = getExistingImports(uri);

            // Find the insert position — after the last import, or after the package declaration
            int insertLine = findImportInsertLine(content);

            for (String fqn : candidates) {
                if (existingImports.contains(fqn)) continue;

                String importStatement = "import " + fqn + "\n";
                TextEdit insertEdit = new TextEdit(
                        new Range(new Position(insertLine, 0), new Position(insertLine, 0)),
                        importStatement);

                CodeAction action = new CodeAction("Import '" + fqn + "'");
                action.setKind(CodeActionKind.QuickFix);
                action.setDiagnostics(Collections.singletonList(diag));

                WorkspaceEdit edit = new WorkspaceEdit();
                edit.setChanges(Collections.singletonMap(uri, Collections.singletonList(insertEdit)));
                action.setEdit(edit);

                actions.add(action);
            }
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError("Failed to create add import actions", e);
        }

        return actions;
    }

    private CodeAction createAddAllMissingImportsAction(String uri, String content,
            List<Diagnostic> diagnostics, List<String> onlyKinds) {
        if (!wantsKind(onlyKinds, CodeActionKind.Source, SOURCE_KIND_ADD_MISSING_IMPORTS)) {
            return null;
        }

        try {
            Set<String> existingImports = getExistingImports(uri);
            Set<String> importsToAdd = new TreeSet<>();
            List<Diagnostic> matchedDiagnostics = new ArrayList<>();

            for (Diagnostic diag : diagnostics) {
                if (!isUnresolvedTypeDiagnostic(diag)) {
                    continue;
                }

                String typeName = extractTypeNameFromMessage(getDiagnosticMessage(diag));
                if (typeName == null || typeName.isEmpty()) {
                    continue;
                }

                List<String> candidates = searchClasspathForType(typeName, uri);
                for (String candidate : candidates) {
                    if (!existingImports.contains(candidate) && !importsToAdd.contains(candidate)) {
                        importsToAdd.add(candidate);
                        matchedDiagnostics.add(diag);
                        break;
                    }
                }
            }

            if (importsToAdd.size() < 2) {
                return null;
            }

            int insertLine = findImportInsertLine(content);
            StringBuilder importBlock = new StringBuilder();
            for (String fqn : importsToAdd) {
                importBlock.append("import ").append(fqn).append("\n");
            }

            TextEdit insertEdit = new TextEdit(
                    new Range(new Position(insertLine, 0), new Position(insertLine, 0)),
                    importBlock.toString());

            CodeAction action = new CodeAction("Add all missing imports");
            action.setKind(SOURCE_KIND_ADD_MISSING_IMPORTS);
            action.setDiagnostics(matchedDiagnostics);

            WorkspaceEdit edit = new WorkspaceEdit();
            edit.setChanges(Collections.singletonMap(uri, Collections.singletonList(insertEdit)));
            action.setEdit(edit);

            return action;
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError("Failed to create add all missing imports action", e);
            return null;
        }
    }

    /**
     * Search the JDT classpath index for types matching the given simple name.
     * Returns a list of fully qualified type names found on the project's classpath.
     */
    private List<String> searchClasspathForType(String simpleName, String uri) {
        List<String> results = new ArrayList<>();

        try {
            // Prefer the Java project that owns this document to avoid
            // cross-project classpath bleed in multi-project workspaces.
            List<IJavaProject> javaProjects = getSearchProjectsForUri(uri);

            if (javaProjects.isEmpty()) {
                GroovyLanguageServerPlugin.logInfo(
                        "[codeaction] No Java project found for import search");
                return results;
            }

            // Create search scope over all project classpaths
            IJavaSearchScope scope = SearchEngine.createJavaSearchScope(
                    javaProjects.toArray(new IJavaProject[0]), IJavaSearchScope.SOURCES
                            | IJavaSearchScope.APPLICATION_LIBRARIES
                            | IJavaSearchScope.SYSTEM_LIBRARIES
                            | IJavaSearchScope.REFERENCED_PROJECTS);

            SearchEngine searchEngine = new SearchEngine();

            // Collect matching type names
            List<TypeNameMatch> matches = new ArrayList<>();
            TypeNameMatchRequestor requestor = new TypeNameMatchRequestor() {
                @Override
                public void acceptTypeNameMatch(TypeNameMatch match) {
                    matches.add(match);
                }
            };

            searchEngine.searchAllTypeNames(
                    null,                                    // any package
                    SearchPattern.R_EXACT_MATCH,
                    simpleName.toCharArray(),                // type simple name
                    SearchPattern.R_EXACT_MATCH | SearchPattern.R_CASE_SENSITIVE,
                    IJavaSearchConstants.TYPE,               // classes, interfaces, enums
                    scope,
                    requestor,
                    IJavaSearchConstants.WAIT_UNTIL_READY_TO_SEARCH,
                    null);

            // Convert matches to FQNs, filtering out internal/synthetic types
            for (TypeNameMatch match : matches) {
                String fqn = match.getFullyQualifiedName();
                if (fqn == null || fqn.isEmpty()) continue;

                // Skip internal types (containing $ for inner classes accessed by outer name)
                if (fqn.contains("$")) continue;

                // Skip sun.* and com.sun.* internal packages
                if (fqn.startsWith("sun.") || fqn.startsWith("com.sun.")
                        || fqn.startsWith("jdk.internal.")) continue;

                results.add(fqn);

                if (results.size() >= MAX_IMPORT_SUGGESTIONS) break;
            }

            // Sort: prefer shorter package paths (more common types first)
            results.sort((a, b) -> {
                // Prefer types from common packages
                int scoreA = packagePriority(a);
                int scoreB = packagePriority(b);
                if (scoreA != scoreB) return Integer.compare(scoreA, scoreB);
                return a.compareTo(b);
            });

            GroovyLanguageServerPlugin.logInfo(
                    "[codeaction] Search for '" + simpleName + "' found " + results.size() + " candidates");

        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError(
                    "[codeaction] JDT type search failed for '" + simpleName + "'", e);
        }

        return results;
    }

    private List<IJavaProject> getSearchProjectsForUri(String uri) {
        List<IJavaProject> scopedProjects = new ArrayList<>();
        Set<String> seenProjectNames = new HashSet<>();

        try {
            String normalizedUri = DocumentManager.normalizeUri(uri);
            URI fileUri = URI.create(normalizedUri);
            IFile[] files = ResourcesPlugin.getWorkspace().getRoot().findFilesForLocationURI(fileUri);

            for (IFile file : files) {
                IProject project = file.getProject();
                if (project == null || !project.isOpen()) {
                    continue;
                }

                IJavaProject javaProject = JavaCore.create(project);
                if (javaProject == null || !javaProject.exists()) {
                    continue;
                }

                if (seenProjectNames.add(project.getName())) {
                    scopedProjects.add(javaProject);
                }
            }
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logInfo(
                    "[codeaction] Failed to scope import search by URI; falling back to all projects: "
                    + e.getMessage());
        }

        if (!scopedProjects.isEmpty()) {
            return scopedProjects;
        }

        // Fallback when the document cannot be mapped to a workspace project.
        List<IJavaProject> allProjects = new ArrayList<>();
        for (IProject project : ResourcesPlugin.getWorkspace().getRoot().getProjects()) {
            if (!project.isOpen()) {
                continue;
            }
            IJavaProject javaProject = JavaCore.create(project);
            if (javaProject != null && javaProject.exists()) {
                allProjects.add(javaProject);
            }
        }

        return allProjects;
    }

    /**
     * Assign a priority score to a package for sorting import suggestions.
     * Lower = better (shown first).
     */
    private int packagePriority(String fqn) {
        if (fqn.startsWith("java.lang.")) return 0;
        if (fqn.startsWith("java.util.")) return 1;
        if (fqn.startsWith("java.io.")) return 2;
        if (fqn.startsWith("java.nio.")) return 3;
        if (fqn.startsWith("java.net.")) return 4;
        if (fqn.startsWith("java.")) return 5;
        if (fqn.startsWith("groovy.")) return 6;
        if (fqn.startsWith("javax.") || fqn.startsWith("jakarta.")) return 7;
        if (fqn.startsWith("org.junit.")) return 8;
        if (fqn.startsWith("spock.")) return 8;
        return 10;
    }

    /**
     * Extract a type name from an error message like "unable to resolve class Foo".
     */
    private String extractTypeNameFromMessage(String message) {
        if (message == null) return null;

        // Common patterns from Groovy compiler
        // "unable to resolve class SomeType"
        // "Groovy:unable to resolve class SomeType"
        String marker = "unable to resolve class ";
        int idx = message.indexOf(marker);
        if (idx >= 0) {
            String rest = message.substring(idx + marker.length()).trim();
            // Take the first word (may be qualified)
            int end = 0;
            while (end < rest.length() &&
                    (Character.isJavaIdentifierPart(rest.charAt(end)) || rest.charAt(end) == '.')) {
                end++;
            }
            String fullName = rest.substring(0, end);
            // Return simple name
            int lastDot = fullName.lastIndexOf('.');
            return lastDot >= 0 ? fullName.substring(lastDot + 1) : fullName;
        }

        return null;
    }

    private String getDiagnosticMessage(Diagnostic diagnostic) {
        Object msgObj = diagnostic.getMessage();
        return msgObj != null ? msgObj.toString() : "";
    }

    private boolean isUnresolvedTypeDiagnostic(Diagnostic diagnostic) {
        String code = getDiagnosticCode(diagnostic);
        String message = getDiagnosticMessage(diagnostic);
        return (code != null && code.startsWith(DIAG_CODE_UNRESOLVED_TYPE))
                || message.contains("unable to resolve class")
                || message.contains("Groovy:unable to resolve class");
    }

    // ================================================================
    // Implement missing interface members
    // ================================================================

    private boolean isMissingInterfaceMemberDiagnostic(Diagnostic diagnostic) {
        String message = getDiagnosticMessage(diagnostic);
        if (message == null || message.isEmpty()) {
            return false;
        }

        return (message.contains("must be declared abstract or the method")
                && message.contains("must be implemented"))
                || message.contains("must implement the inherited abstract method");
    }

    private CodeAction createImplementMissingInterfaceMembersAction(String uri, String content,
            Diagnostic diag) {
        try {
            ModuleNode module = documentManager.getGroovyAST(uri);
            if (module == null) {
                return null;
            }

            int targetLine = Math.max(1, diag.getRange().getStart().getLine() + 1);
            ClassNode targetClass = findEnclosingClass(module, targetLine);
            if (targetClass == null) {
                String className = extractClassSimpleNameFromMessage(getDiagnosticMessage(diag));
                targetClass = findClassBySimpleName(module, className);
            }

            if (targetClass == null || targetClass.isInterface()) {
                return null;
            }

            List<MethodNode> missingMethods = findMissingInterfaceMethods(targetClass, module);
            if (missingMethods.isEmpty()) {
                return null;
            }

            int insertLine = findClassInsertLine(targetClass, content);
            String insertionText = buildMissingMethodStubsText(targetClass, missingMethods, content, insertLine);
            if (insertionText.isEmpty()) {
                return null;
            }

            TextEdit insertEdit = new TextEdit(
                    new Range(new Position(insertLine, 0), new Position(insertLine, 0)),
                    insertionText);

            CodeAction action = new CodeAction(
                    missingMethods.size() == 1
                            ? "Implement missing interface member"
                            : "Implement missing interface members");
            action.setKind(CodeActionKind.QuickFix);
            action.setDiagnostics(Collections.singletonList(diag));
            action.setIsPreferred(true);

            WorkspaceEdit edit = new WorkspaceEdit();
            edit.setChanges(Collections.singletonMap(uri, Collections.singletonList(insertEdit)));
            action.setEdit(edit);

            return action;
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError("Failed to create implement missing members action", e);
            return null;
        }
    }

    private List<MethodNode> findMissingInterfaceMethods(ClassNode targetClass, ModuleNode currentModule) {
        List<MethodNode> requiredMethods = new ArrayList<>();
        Set<String> requiredSignatures = new TreeSet<>();
        Set<String> visitedInterfaces = new HashSet<>();

        ClassNode[] interfaces = targetClass.getInterfaces();
        if (interfaces == null || interfaces.length == 0) {
            return Collections.emptyList();
        }

        for (ClassNode ifaceRef : interfaces) {
            collectRequiredInterfaceMethodsRecursive(
                    ifaceRef,
                    currentModule,
                    requiredMethods,
                    requiredSignatures,
                    visitedInterfaces);
        }

        List<MethodNode> missingMethods = new ArrayList<>();
        for (MethodNode required : requiredMethods) {
            if (!hasConcreteMethodInHierarchy(targetClass, required)) {
                missingMethods.add(required);
            }
        }

        return missingMethods;
    }

    private void collectRequiredInterfaceMethodsRecursive(ClassNode ifaceRef,
            ModuleNode currentModule,
            List<MethodNode> requiredMethods,
            Set<String> requiredSignatures,
            Set<String> visitedInterfaces) {
        if (ifaceRef == null) {
            return;
        }

        ClassNode resolved = TraitMemberResolver.resolveTraitClassNode(ifaceRef, currentModule, documentManager);
        String interfaceName = resolved.getName();
        if (interfaceName == null || !visitedInterfaces.add(interfaceName)) {
            return;
        }

        for (MethodNode method : resolved.getMethods()) {
            if (!isMethodRequiredForImplementation(method)) {
                continue;
            }
            String signature = methodSignatureKey(method);
            if (requiredSignatures.add(signature)) {
                requiredMethods.add(method);
            }
        }

        ClassNode[] superInterfaces = resolved.getInterfaces();
        if (superInterfaces != null) {
            for (ClassNode superInterface : superInterfaces) {
                collectRequiredInterfaceMethodsRecursive(
                        superInterface,
                        currentModule,
                        requiredMethods,
                        requiredSignatures,
                        visitedInterfaces);
            }
        }
    }

    private boolean isMethodRequiredForImplementation(MethodNode method) {
        if (method == null) {
            return false;
        }

        String name = method.getName();
        if (name == null || name.isEmpty() || name.startsWith("$")) {
            return false;
        }

        int modifiers = method.getModifiers();
        if (!Modifier.isAbstract(modifiers)
                || Modifier.isStatic(modifiers)
                || Modifier.isPrivate(modifiers)) {
            return false;
        }

        ClassNode declaringClass = method.getDeclaringClass();
        if (declaringClass != null) {
            String declaringName = declaringClass.getName();
            if ("java.lang.Object".equals(declaringName)
                    || "groovy.lang.GroovyObject".equals(declaringName)) {
                return false;
            }
        }

        return true;
    }

    private boolean hasConcreteMethodInHierarchy(ClassNode targetClass, MethodNode requiredMethod) {
        for (ClassNode current = targetClass; current != null; current = current.getSuperClass()) {
            List<MethodNode> candidates = current.getDeclaredMethods(requiredMethod.getName());
            for (MethodNode candidate : candidates) {
                if (hasSameParameterTypes(candidate, requiredMethod)
                        && !Modifier.isAbstract(candidate.getModifiers())) {
                    return true;
                }
            }
        }
        return false;
    }

    private boolean hasSameParameterTypes(MethodNode left, MethodNode right) {
        Parameter[] leftParams = left.getParameters();
        Parameter[] rightParams = right.getParameters();
        if (leftParams == null || rightParams == null) {
            return (leftParams == null || leftParams.length == 0)
                    && (rightParams == null || rightParams.length == 0);
        }
        if (leftParams.length != rightParams.length) {
            return false;
        }

        for (int i = 0; i < leftParams.length; i++) {
            String leftType = normalizeTypeName(leftParams[i].getType());
            String rightType = normalizeTypeName(rightParams[i].getType());
            if (!leftType.equals(rightType)) {
                return false;
            }
        }

        return true;
    }

    private String methodSignatureKey(MethodNode method) {
        StringBuilder sb = new StringBuilder();
        sb.append(method.getName()).append('(');
        Parameter[] parameters = method.getParameters();
        if (parameters != null) {
            for (int i = 0; i < parameters.length; i++) {
                if (i > 0) {
                    sb.append(',');
                }
                sb.append(normalizeTypeName(parameters[i].getType()));
            }
        }
        sb.append(')');
        return sb.toString();
    }

    private String normalizeTypeName(ClassNode type) {
        if (type == null) {
            return "def";
        }
        if (type.isArray()) {
            return normalizeTypeName(type.getComponentType()) + "[]";
        }
        String name = type.getName();
        if (name == null || name.isEmpty()) {
            name = type.getNameWithoutPackage();
        }
        return name == null || name.isEmpty() ? "def" : name;
    }

    private int findClassInsertLine(ClassNode targetClass, String content) {
        String[] lines = content.split("\\n", -1);
        if (lines.length == 0) {
            return 0;
        }

        int startLine = Math.max(0, targetClass.getLineNumber() - 1);
        int endLine = Math.max(startLine, targetClass.getLastLineNumber() - 1);
        endLine = Math.min(endLine, lines.length - 1);

        for (int line = endLine; line >= startLine; line--) {
            if (lines[line].trim().equals("}")) {
                return line;
            }
        }

        return endLine;
    }

    private String buildMissingMethodStubsText(ClassNode targetClass,
            List<MethodNode> missingMethods,
            String content,
            int insertLine) {
        String[] lines = content.split("\\n", -1);
        int classLine = Math.max(0, targetClass.getLineNumber() - 1);

        String classIndent = classLine < lines.length ? leadingWhitespace(lines[classLine]) : "";
        String indentUnit = inferIndentUnit(lines, classIndent, classLine, insertLine);
        String methodIndent = classIndent + indentUnit;
        String bodyIndent = methodIndent + indentUnit;

        StringBuilder sb = new StringBuilder();
        if (insertLine > 0 && insertLine - 1 < lines.length && !lines[insertLine - 1].trim().isEmpty()) {
            sb.append("\n");
        }

        for (int i = 0; i < missingMethods.size(); i++) {
            MethodNode method = missingMethods.get(i);

            sb.append(methodIndent).append("@Override\n");
            sb.append(methodIndent)
                    .append(renderType(method.getReturnType()))
                    .append(' ')
                    .append(method.getName())
                    .append('(')
                    .append(renderParameters(method.getParameters()))
                    .append(") {\n");
            sb.append(bodyIndent)
                    .append("throw new UnsupportedOperationException(\"Method '")
                    .append(method.getName())
                    .append("' is not implemented\")\n");
            sb.append(methodIndent).append("}\n");

            if (i + 1 < missingMethods.size()) {
                sb.append("\n");
            }
        }

        sb.append("\n");
        return sb.toString();
    }

    private String renderType(ClassNode type) {
        if (type == null) {
            return "def";
        }
        if (type.isArray()) {
            return renderType(type.getComponentType()) + "[]";
        }
        String simpleName = type.getNameWithoutPackage();
        if (simpleName == null || simpleName.isEmpty()) {
            simpleName = type.getName();
        }
        return simpleName == null || simpleName.isEmpty() ? "def" : simpleName;
    }

    private String renderParameters(Parameter[] parameters) {
        if (parameters == null || parameters.length == 0) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < parameters.length; i++) {
            if (i > 0) {
                sb.append(", ");
            }
            Parameter parameter = parameters[i];
            String name = sanitizeParameterName(parameter.getName(), i + 1);
            sb.append(renderType(parameter.getType())).append(' ').append(name);
        }
        return sb.toString();
    }

    private String sanitizeParameterName(String rawName, int position) {
        if (rawName == null || rawName.isEmpty()) {
            return "arg" + position;
        }
        if (!Character.isJavaIdentifierStart(rawName.charAt(0))) {
            return "arg" + position;
        }
        for (int i = 1; i < rawName.length(); i++) {
            if (!Character.isJavaIdentifierPart(rawName.charAt(i))) {
                return "arg" + position;
            }
        }
        return rawName;
    }

    private String inferIndentUnit(String[] lines, String classIndent, int classLine, int insertLine) {
        int start = Math.max(0, classLine + 1);
        int end = Math.min(lines.length - 1, Math.max(classLine, insertLine));

        for (int i = start; i <= end; i++) {
            String line = lines[i];
            if (line.trim().isEmpty()) {
                continue;
            }

            String indent = leadingWhitespace(line);
            if (indent.length() > classIndent.length() && indent.startsWith(classIndent)) {
                String delta = indent.substring(classIndent.length());
                if (!delta.isEmpty()) {
                    return delta;
                }
            }
        }

        return "    ";
    }

    private String leadingWhitespace(String line) {
        int i = 0;
        while (i < line.length()) {
            char c = line.charAt(i);
            if (c != ' ' && c != '\t') {
                break;
            }
            i++;
        }
        return line.substring(0, i);
    }

    private ClassNode findEnclosingClass(ModuleNode module, int targetLine) {
        ClassNode best = null;
        for (ClassNode classNode : module.getClasses()) {
            int start = classNode.getLineNumber();
            int end = classNode.getLastLineNumber();
            if (start > 0 && end >= start && targetLine >= start && targetLine <= end) {
                if (best == null || start >= best.getLineNumber()) {
                    best = classNode;
                }
            } else if (start > 0 && start <= targetLine) {
                if (best == null || start >= best.getLineNumber()) {
                    best = classNode;
                }
            }
        }
        return best;
    }

    private ClassNode findClassBySimpleName(ModuleNode module, String simpleName) {
        if (simpleName == null || simpleName.isEmpty()) {
            return null;
        }
        for (ClassNode classNode : module.getClasses()) {
            if (simpleName.equals(classNode.getNameWithoutPackage())) {
                return classNode;
            }
        }
        return null;
    }

    private String extractClassSimpleNameFromMessage(String message) {
        if (message == null || message.isEmpty()) {
            return null;
        }

        int firstQuote = message.indexOf('\'');
        if (firstQuote >= 0) {
            int secondQuote = message.indexOf('\'', firstQuote + 1);
            if (secondQuote > firstQuote + 1) {
                String candidate = message.substring(firstQuote + 1, secondQuote).trim();
                int dot = candidate.lastIndexOf('.');
                return dot >= 0 ? candidate.substring(dot + 1) : candidate;
            }
        }

        String marker = "The type ";
        int idx = message.indexOf(marker);
        if (idx >= 0) {
            String rest = message.substring(idx + marker.length()).trim();
            int end = 0;
            while (end < rest.length() &&
                    (Character.isJavaIdentifierPart(rest.charAt(end)) || rest.charAt(end) == '.')) {
                end++;
            }
            if (end > 0) {
                String candidate = rest.substring(0, end);
                int dot = candidate.lastIndexOf('.');
                return dot >= 0 ? candidate.substring(dot + 1) : candidate;
            }
        }

        return null;
    }

    /**
     * Get the set of fully qualified names already imported in a document.
     */
    private Set<String> getExistingImports(String uri) {
        Set<String> imports = new TreeSet<>();
        ModuleNode ast = documentManager.getGroovyAST(uri);
        if (ast != null) {
            for (ImportNode imp : ast.getImports()) {
                if (imp.getType() != null) {
                    imports.add(imp.getType().getName());
                }
            }
        }
        return imports;
    }

    /**
     * Find the line number where new imports should be inserted.
     * Returns the line after the last import statement, or after the package
     * declaration, or line 0 if neither exists.
     */
    private int findImportInsertLine(String content) {
        String[] lines = content.split("\n", -1);
        int lastImportLine = -1;
        int packageLine = -1;

        for (int i = 0; i < lines.length; i++) {
            String trimmed = lines[i].trim();
            if (trimmed.startsWith("package ")) {
                packageLine = i;
            }
            if (trimmed.startsWith("import ")) {
                lastImportLine = i;
            }
            // Stop scanning after first class/interface/enum/trait/def
            if (trimmed.startsWith("class ") || trimmed.startsWith("interface ")
                    || trimmed.startsWith("enum ") || trimmed.startsWith("trait ")
                    || trimmed.startsWith("@") || trimmed.startsWith("def ")
                    || trimmed.startsWith("public ") || trimmed.startsWith("abstract ")
                    || trimmed.startsWith("final ")) {
                break;
            }
        }

        if (lastImportLine >= 0) {
            return lastImportLine + 1;
        }
        if (packageLine >= 0) {
            return packageLine + 2; // blank line after package
        }
        return 0;
    }

    // ================================================================
    // Organize imports
    // ================================================================

    private CodeAction createOrganizeImportsAction(String uri, String content, List<String> onlyKinds) {
        if (!wantsKind(onlyKinds, CodeActionKind.Source, CodeActionKind.SourceOrganizeImports)) {
            return null;
        }

        List<TextEdit> edits = createRemoveUnusedImportEdits(uri, content);
        if (edits.isEmpty()) {
            return null;
        }

        CodeAction action = new CodeAction("Organize imports");
        action.setKind(CodeActionKind.SourceOrganizeImports);

        WorkspaceEdit edit = new WorkspaceEdit();
        edit.setChanges(Collections.singletonMap(uri, edits));
        action.setEdit(edit);

        return action;
    }

    private CodeAction createRemoveAllUnusedImportsAction(String uri, String content, List<String> onlyKinds) {
        if (!wantsKind(onlyKinds, CodeActionKind.Source, SOURCE_KIND_REMOVE_UNUSED_IMPORTS)) {
            return null;
        }

        List<TextEdit> edits = createRemoveUnusedImportEdits(uri, content);
        if (edits.isEmpty()) {
            return null;
        }

        CodeAction action = new CodeAction("Remove all unused imports");
        action.setKind(SOURCE_KIND_REMOVE_UNUSED_IMPORTS);

        WorkspaceEdit edit = new WorkspaceEdit();
        edit.setChanges(Collections.singletonMap(uri, edits));
        action.setEdit(edit);

        return action;
    }

    private CodeAction createRemoveAllUnusedImportsQuickFixAction(String uri, String content,
            List<Diagnostic> diagnostics) {
        List<TextEdit> edits = createRemoveUnusedImportEdits(uri, content);
        if (edits.isEmpty()) {
            return null;
        }

        CodeAction action = new CodeAction("Remove all unused imports");
        action.setKind(CodeActionKind.QuickFix);
        if (diagnostics != null && !diagnostics.isEmpty()) {
            action.setDiagnostics(diagnostics);
        }

        WorkspaceEdit edit = new WorkspaceEdit();
        edit.setChanges(Collections.singletonMap(uri, edits));
        action.setEdit(edit);

        return action;
    }

    private CodeAction createAddAllMissingImportsQuickFixAction(String uri, String content,
            List<Diagnostic> diagnostics) {
        try {
            Set<String> existingImports = getExistingImports(uri);
            Set<String> importsToAdd = new TreeSet<>();
            List<Diagnostic> matchedDiagnostics = new ArrayList<>();

            for (Diagnostic diag : diagnostics) {
                if (!isUnresolvedTypeDiagnostic(diag)) {
                    continue;
                }

                String typeName = extractTypeNameFromMessage(getDiagnosticMessage(diag));
                if (typeName == null || typeName.isEmpty()) {
                    continue;
                }

                List<String> candidates = searchClasspathForType(typeName, uri);
                for (String candidate : candidates) {
                    if (!existingImports.contains(candidate) && !importsToAdd.contains(candidate)) {
                        importsToAdd.add(candidate);
                        matchedDiagnostics.add(diag);
                        break;
                    }
                }
            }

            if (importsToAdd.size() < 2) {
                return null;
            }

            int insertLine = findImportInsertLine(content);
            StringBuilder importBlock = new StringBuilder();
            for (String fqn : importsToAdd) {
                importBlock.append("import ").append(fqn).append("\n");
            }

            TextEdit insertEdit = new TextEdit(
                    new Range(new Position(insertLine, 0), new Position(insertLine, 0)),
                    importBlock.toString());

            CodeAction action = new CodeAction("Add all missing imports");
            action.setKind(CodeActionKind.QuickFix);
            action.setDiagnostics(matchedDiagnostics);

            WorkspaceEdit edit = new WorkspaceEdit();
            edit.setChanges(Collections.singletonMap(uri, Collections.singletonList(insertEdit)));
            action.setEdit(edit);

            return action;
        } catch (Exception e) {
            GroovyLanguageServerPlugin.logError("Failed to create add all missing imports quick fix action", e);
            return null;
        }
    }

    private List<TextEdit> createRemoveUnusedImportEdits(String uri, String content) {
        ModuleNode ast = documentManager.getGroovyAST(uri);
        if (ast == null) return Collections.emptyList();

        Set<String> unusedImportLines = UnusedImportDetector.findUnusedImportLines(ast, content);
        if (unusedImportLines.isEmpty()) return Collections.emptyList();

        List<TextEdit> edits = new ArrayList<>();
        String[] lines = content.split("\n", -1);

        for (int i = lines.length - 1; i >= 0; i--) {
            String trimmed = lines[i].trim();
            if (unusedImportLines.contains(trimmed)) {
                edits.add(new TextEdit(
                        new Range(new Position(i, 0), new Position(i + 1, 0)),
                        ""));
            }
        }

        return edits;
    }

    private boolean wantsKind(List<String> onlyKinds, String... expectedKinds) {
        if (onlyKinds == null) {
            return true;
        }

        for (String expectedKind : expectedKinds) {
            if (onlyKinds.contains(expectedKind)) {
                return true;
            }
        }

        return false;
    }
}
