#
# Groovy Language Server — Linux configuration
#
osgi.bundles=\
 reference\:file\:org.apache.felix.scr-2.2.12.jar@1\:start,\
 reference\:file\:org.eclipse.equinox.common_3.20.300.jar@2\:start,\
 reference\:file\:org.eclipse.equinox.registry_3.12.600.jar@start,\
 reference\:file\:org.eclipse.equinox.preferences_3.12.100.jar@start,\
 reference\:file\:org.eclipse.equinox.app_1.7.500.jar@start,\
 reference\:file\:org.eclipse.core.runtime_3.34.100.jar@start,\
 reference\:file\:org.eclipse.core.contenttype_3.9.800.jar@start,\
 reference\:file\:org.eclipse.core.jobs_3.15.700.jar@start,\
 reference\:file\:org.eclipse.core.filesystem_1.11.400.jar@start,\
 reference\:file\:org.eclipse.core.resources_3.23.100.jar@start,\
 reference\:file\:org.eclipse.core.expressions_3.9.500.jar,\
 reference\:file\:org.eclipse.core.commands_3.12.500.jar,\
 reference\:file\:org.eclipse.core.filebuffers_3.8.500.jar,\
 reference\:file\:org.eclipse.core.variables_3.6.700.jar,\
 reference\:file\:org.eclipse.text_3.14.500.jar,\
 reference\:file\:org.eclipse.jdt.core.compiler.batch_3.44.0.v202512311652-e2512.jar,\
 reference\:file\:org.eclipse.jdt.core_3.44.0.v202512311652-e2512.jar@start,\
 reference\:file\:org.eclipse.jdt.launching_3.24.0.jar,\
 reference\:file\:org.eclipse.jdt.debug_3.25.0.jar,\
 reference\:file\:org.eclipse.debug.core_3.23.200.jar,\
 reference\:file\:org.eclipse.ltk.core.refactoring_3.15.100.jar,\
 reference\:file\:org.eclipse.search.core_3.16.600.jar,\
 reference\:file\:org.eclipse.lsp4j_1.0.0.jar,\
 reference\:file\:org.eclipse.lsp4j.jsonrpc_1.0.0.jar,\
 reference\:file\:gson-2.11.0.jar,\
 reference\:file\:error_prone_annotations-2.27.0.jar,\
 reference\:file\:jna-5.18.1.jar,\
 reference\:file\:jna-platform-5.18.1.jar,\
 reference\:file\:org.osgi.service.prefs_1.1.2.jar,\
 reference\:file\:org.osgi.service.component_1.5.1.jar,\
 reference\:file\:org.osgi.namespace.extender_1.0.1.jar,\
 reference\:file\:org.osgi.util.function_1.2.0.jar,\
 reference\:file\:org.osgi.util.promise_1.3.0.jar,\
 reference\:file\:osgi.annotation_8.1.0.jar,\
 reference\:file\:org.codehaus.groovy_5.0.3.v202512311652-e2512.jar@start,\
 reference\:file\:org.eclipse.jdt.groovy.core_6.0.0.v202512311652-e2512.jar@start,\
 reference\:file\:org.eclipse.groovy.ls.core_0.1.0.jar@start

eclipse.application=org.eclipse.groovy.ls.core.id1
eclipse.product=org.eclipse.groovy.ls.core.product
osgi.bundles.defaultStartLevel=4
osgi.configuration.cascaded=false
