package org.eclipse.groovy.ls.perf;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Formats {@link PerformanceResult}s into Markdown and CSV reports, and prints
 * a human-readable summary to stdout.
 */
public class PerformanceReporter {

    private final Path reportDir;

    public PerformanceReporter(Path reportDir) {
        this.reportDir = reportDir;
    }

    /**
     * Generate all report formats for the given results.
     */
    public void report(List<PerformanceResult> results) throws IOException {
        Files.createDirectories(reportDir);
        writeMarkdown(results);
        writeCsv(results);
        printSummary(results);
    }

    // ---- Markdown report ----

    private void writeMarkdown(List<PerformanceResult> results) throws IOException {
        Path file = reportDir.resolve("results.md");
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(file))) {
            w.println("# Groovy Language Server — Performance Test Results");
            w.println();
            w.printf("**Date**: %s%n%n", LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
            w.println("| Feature | Iterations | p50 (ms) | p95 (ms) | p99 (ms) | Max (ms) | Mean (ms) | Throughput (ops/s) |");
            w.println("|---------|-----------|----------|----------|----------|----------|-----------|-------------------|");
            for (PerformanceResult r : results) {
                w.printf("| %s | %d | %d | %d | %d | %d | %.1f | %.2f |%n",
                        r.getFeatureName(),
                        r.getIterationCount(),
                        r.getP50(),
                        r.getP95(),
                        r.getP99(),
                        r.getMax(),
                        r.getMean(),
                        r.getThroughputOpsPerSec());
            }
            w.println();
            w.println("---");
            w.println("*Generated by `org.eclipse.groovy.ls.perf`*");
        }
        System.out.println("[PerfReporter] Markdown report written to: " + file.toAbsolutePath());
    }

    // ---- CSV report (for trend analysis) ----

    private void writeCsv(List<PerformanceResult> results) throws IOException {
        Path file = reportDir.resolve("results.csv");
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(file))) {
            w.println("timestamp,feature,iterations,p50_ms,p95_ms,p99_ms,max_ms,mean_ms,throughput_ops_per_sec");
            String ts = LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
            for (PerformanceResult r : results) {
                w.printf("%s,%s,%d,%d,%d,%d,%d,%.1f,%.2f%n",
                        ts,
                        r.getFeatureName(),
                        r.getIterationCount(),
                        r.getP50(),
                        r.getP95(),
                        r.getP99(),
                        r.getMax(),
                        r.getMean(),
                        r.getThroughputOpsPerSec());
            }
        }
        System.out.println("[PerfReporter] CSV report written to: " + file.toAbsolutePath());
    }

    // ---- Console summary ----

    private void printSummary(List<PerformanceResult> results) {
        System.out.println();
        System.out.println("╔══════════════════════════════════════════════════════════════════════════╗");
        System.out.println("║              GROOVY LANGUAGE SERVER — PERFORMANCE RESULTS               ║");
        System.out.println("╠══════════════════════════════════════════════════════════════════════════╣");
        for (PerformanceResult r : results) {
            System.out.printf("║  %-42s  p95=%5d ms  max=%5d ms ║%n",
                    truncate(r.getFeatureName(), 42), r.getP95(), r.getMax());
        }
        System.out.println("╚══════════════════════════════════════════════════════════════════════════╝");
        System.out.println();
    }

    private static String truncate(String s, int maxLen) {
        return s.length() <= maxLen ? s : s.substring(0, maxLen - 1) + "…";
    }
}
